---
title: "Code_COG_DESeq2"
author: "Edna Chiang"
date: "3/8/2021"
output: html_document
---

### Load Libraries
```{r}
library('readr')
library('pgirmess')
library('ggplot2')
library('grid')
library('phyloseq')
library('DESeq2')
library('phangorn')
library('vegan')
library('pheatmap')
library('RColorBrewer')
library('gplots')
library('tidyr')
library('dplyr')
library('stringr')
library('lme4')
library('picante')
library('ggdendro')
library('fitdistrplus')
library('amap')
library('labdsv')
library('NBPSeq')
theme_set(theme_bw())
set.seed(1)
```

### Load Functions
```{r}
source('scripts/misc.R')
source('scripts/simper.R')
source('scripts/pairwise.adonis.R')
```

### COG - Load physeq objects (normalized)
```{r}
load("cog.phy.Rdata")
load("cog.cat.phy.Rdata")
meta <- read.csv('dbcan/dbcan.spades.metadata.csv', row.names=1)
```


### Try DESeq2 binomial test on normalized COG category counts
```{r}
cog.cat.norm.dds <- phyloseq_to_deseq2(cog.cat.phy, design = ~Season)
  # Counts are rounded to integer
cog.cat.norm.dds$Season <- factor(cog.cat.norm.dds$Season, levels=c("Summer", "Winter", "Spring"))

cog.cat.norm.dds <- estimateSizeFactors(cog.cat.norm.dds)
sizeFactors(cog.cat.norm.dds) <- 1

cog.cat.norm.dds <- estimateDispersions(cog.cat.norm.dds, fitType = "mean")

cog.cat.norm.dds <- nbinomWaldTest(cog.cat.norm.dds)

cog.cat.norm.sw <- results(cog.cat.norm.dds, contrast = c("Season", "Summer", "Winter"))
cog.cat.norm.sw[which(cog.cat.norm.sw$padj < 0.05)]

cog.cat.norm.sp <- results(cog.cat.norm.dds, contrast = c("Season", "Summer", "Spring"))
cog.cat.norm.sp[which(cog.cat.norm.sp$padj < 0.05)]

cog.cat.norm.wp <- results(cog.cat.norm.dds, contrast = c("Season", "Winter", "Spring"))
cog.cat.norm.wp.sig <- cog.cat.norm.wp[which(cog.cat.norm.wp$padj < 0.05),]

```


### Try DESeq2 on raw COG category data
```{r}
# Load data
load("cog.phy.Rdata")
load("cog.cat.phy.Rdata")
meta <- read.csv('dbcan/dbcan.spades.metadata.csv', row.names=1)

cog.cat <- read.csv('cog/cog.category.raw.csv', header = T)
rownames(cog.cat) <- cog.cat[,1]
cog.cat <- cog.cat[,-1]
colnames(cog.cat) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")

cog.cat.rphy <- merge_phyloseq(otu_table(cog.cat, taxa_are_rows = T), tax_table(cog.cat.phy), sample_data(cog.cat.phy))

cog.cat.rdds <- phyloseq_to_deseq2(cog.cat.rphy, ~Season)
cog.cat.rdds$Season <- factor(cog.cat.rdds$Season, levels=c("Summer", "Winter", "Spring"))

cog.cat.rdds <- DESeq(cog.cat.rdds)


cog.cat.sw <- results(cog.cat.rdds, contrast = c("Season", "Summer", "Winter"))
cog.cat.sw[which(cog.cat.sw$padj < 0.05)]

cog.cat.sp <- results(cog.cat.rdds, contrast = c("Season", "Summer", "Spring"))
cog.cat.sp[which(cog.cat.sp$padj < 0.05)]

cog.cat.wp <- results(cog.cat.rdds, contrast = c("Season", "Winter", "Spring"))
cog.cat.wp.sig <- cog.cat.wp[which(cog.cat.wp$padj < 0.05),]
cog.cat.wp.sig[which(cog.cat.wp.sig$log2FoldChange > 0),]
  # Enriched in Winter compared to Spring (positive log2FoldChange)  
  # M
cog.cat.wp.sig[which(cog.cat.wp.sig$log2FoldChange < 0),]
  # Enriched in Spring compared to Winter (positive log2FoldChange)  
  # G, K, T, V
```



### Try DESeq2 binomial test on normalized COG counts
```{r}
cog.norm.dds <- phyloseq_to_deseq2(cog.phy, design = ~Season)
  # Counts are rounded to integer
cog.norm.dds$Season <- factor(cog.norm.dds$Season, levels=c("Summer", "Winter", "Spring"))

cog.norm.dds <- estimateSizeFactors(cog.norm.dds)
sizeFactors(cog.norm.dds) <- 1

cog.norm.dds <- estimateDispersions(cog.norm.dds, fitType = "mean")

cog.norm.dds <- nbinomWaldTest(cog.norm.dds)

cog.norm.sw <- results(cog.norm.dds, contrast = c("Season", "Summer", "Winter"))
cog.norm.sw[which(cog.norm.sw$padj < 0.05)]

cog.norm.sp <- results(cog.norm.dds, contrast = c("Season", "Summer", "Spring"))
cog.norm.sp[which(cog.norm.sp$padj < 0.05)]

cog.norm.wp <- results(cog.norm.dds, contrast = c("Season", "Winter", "Spring"))
cog.norm.wp[which(cog.norm.wp$padj < 0.05),]

```
### Try DESeq2 on raw COG data
```{r}
# Load data
load("cog.phy.Rdata")
load("cog.cat.phy.Rdata")
meta <- read.csv('dbcan/dbcan.spades.metadata.csv', row.names=1)

cog.counts <- read.csv('cog/COG.table.tab', header = T, sep = "\t")
rownames(cog.counts) <- cog.counts$COG
cog.counts <- cog.counts[,-1]
colnames(cog.counts) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")

cog.rphy <- merge_phyloseq(otu_table(cog.counts, taxa_are_rows = T), tax_table(cog.phy), sample_data(cog.phy))

cog.rdds <- phyloseq_to_deseq2(cog.rphy, ~Season)
cog.rdds$Season <- factor(cog.rdds$Season, levels=c("Summer", "Winter", "Spring"))

cog.rdds <- DESeq(cog.rdds)


cog.sw <- results(cog.rdds, contrast = c("Season", "Summer", "Winter"))
cog.sw[which(cog.sw$padj < 0.05),]
# lots

cog.sp <- results(cog.rdds, contrast = c("Season", "Summer", "Spring"))
cog.sp[which(cog.sp$padj < 0.05),]
# lots

cog.wp <- results(cog.rdds, contrast = c("Season", "Winter", "Spring"))
cog.wp.sig <- cog.wp[which(cog.wp$padj < 0.05),]
cog.wp.sig[which(cog.wp.sig$log2FoldChange > 0),]
  # Enriched in Winter compared to Spring (positive log2FoldChange)  
  # COG0457, COG0760, COG0774, COG1452, COG1463, COG1629, COG2825, COG2885, COG3637, COG4775
cog.wp.sig[which(cog.wp.sig$log2FoldChange < 0),]
  # Enriched in Spring compared to Winter (positive log2FoldChange)  
  # G, K, T, V
```