---
title: "Kaiju Code"
author: "Edna Chiang"
date: "1/26/2021"
output: html_document
---

### Load Libraries
```{r}
library('readr')
library('pgirmess')
library('ggplot2')
library('grid')
library('phyloseq')
library('DESeq2')
library('phangorn')
library('vegan')
library('pheatmap')
library('RColorBrewer')
library('gplots')
library('tidyr')
library('dplyr')
library('stringr')
library('lme4')
library('picante')
library('ggdendro')
theme_set(theme_bw())
set.seed(1)
```

### Load Functions
```{r}
source('scripts/misc.R')
source('scripts/import.phylum.sum.R')
source('scripts/import.class.sum.R')
source('scripts/import.order.sum.R')
source('scripts/import.family.sum.R')
source('scripts/import.genus.sum.R')
source('scripts/import.species.sum.R')
```

### No Host
```{r}
########## Domain ##########
# Load files
domain <- read.csv('kaiju/nohost/domain/domain.csv', header=T)
domain$Season <- ordered(domain$Season, levels=c("Summer", "Winter", "Spring"))
meta <- read.csv('metadata.csv', header=T)
meta$Season <- ordered(meta$Season, levels=c("Summer", "Winter", "Spring"))

# Calculate relative abundance for total sequences
domain.ra <- domain
domain.ra$Archaea <- (domain.ra$Archaea / domain.ra$Total_Sequences)
domain.ra$Bacteria <- (domain.ra$Bacteria / domain.ra$Total_Sequences)
domain.ra$Eukaryota <- (domain.ra$Eukaryota / domain.ra$Total_Sequences)
domain.ra$Viruses <- (domain.ra$Viruses / domain.ra$Total_Sequences)
domain.ra$Unclassified <- (domain.ra$Total_Unclassified / domain.ra$Total_Sequences)

# Calculate relative abundance for classified sequences
domain.clas.ra <- domain
domain.clas.ra$Archaea <- (domain.clas.ra$Archaea / domain.clas.ra$Total_Classified)
domain.clas.ra$Bacteria <- (domain.clas.ra$Bacteria / domain.clas.ra$Total_Classified)
domain.clas.ra$Eukaryota <- (domain.clas.ra$Eukaryota / domain.clas.ra$Total_Classified)
domain.clas.ra$Viruses <- (domain.clas.ra$Viruses / domain.clas.ra$Total_Classified)

# Summarize all sequences
domain.sum <- domain.ra %>%
  group_by(Season) %>%
  summarize(Archaea_Mean = mean(Archaea)*100,
            Bacteria_Mean = mean(Bacteria)*100,
            Eukaryota_Mean = mean(Eukaryota)*100,
            Viruses_Mean = mean(Viruses)*100,
            Unclassified_Mean = mean(Unclassified)*100,
            Archaea_SD = sd(Archaea)*100,
            Bacteria_SD = sd(Bacteria)*100,
            Eukaryota_SD = sd(Eukaryota)*100,
            Viruses_SD = sd(Viruses)*100,
            Unclassified_SD = sd(Unclassified)*100,
            Archaea_SE = se(Archaea)*100,
            Bacteria_SE = se(Bacteria)*100,
            Eukaryota_SE = se(Eukaryota)*100,
            Viruses_SE = se(Viruses)*100,
            Unclassified_SE = se(Unclassified)*100)

# Summarize only classified sequences
domain.clas.sum <- domain.clas.ra %>%
  group_by(Season) %>%
  summarize(Archaea_Mean = mean(Archaea)*100,
            Bacteria_Mean = mean(Bacteria)*100,
            Eukaryota_Mean = mean(Eukaryota)*100,
            Viruses_Mean = mean(Viruses)*100,
            Archaea_SD = sd(Archaea)*100,
            Bacteria_SD = sd(Bacteria)*100,
            Eukaryota_SD = sd(Eukaryota)*100,
            Viruses_SD = sd(Viruses)*100,
            Archaea_SE = se(Archaea)*100,
            Bacteria_SE = se(Bacteria)*100,
            Eukaryota_SE = se(Eukaryota)*100,
            Viruses_SE = se(Viruses)*100)

# Create domain all seqs dataframe for plotting
domain.df <- data.frame(matrix(NA, nrow=15, ncol=5))
colnames(domain.df) <- c("Season", "Domain", "Mean", "SD", "SE")
domain.df$Season <- c(rep("Summer", 5), rep("Winter", 5), rep("Spring", 5))
domain.df$Season <- ordered(domain.df$Season, levels=c("Summer", "Winter", "Spring"))
domain.df$Domain <- c(rep(c("Archaea", "Bacteria", "Eukaryota", "Viruses", "Unclassified"), 3))
domain.df$Domain <- ordered(domain.df$Domain, levels=c("Archaea", "Bacteria", "Eukaryota", "Viruses",
                                                       "Unclassified"))
domain.df$Mean <- as.numeric(c(domain.sum[1,2:6], domain.sum[2, 2:6], domain.sum[3, 2:6]))
domain.df$SD <- as.numeric(c(domain.sum[1, 7:11], domain.sum[2, 7:11], domain.sum[3, 7:11]))
domain.df$SE <- as.numeric(c(domain.sum[1, 12:16], domain.sum[2, 12:16], domain.sum[3, 12:16]))

# Create domain classified seqs dataframe for plotting
domain.clas.df <- data.frame(matrix(NA, nrow=12, ncol=5))
colnames(domain.clas.df) <- c("Season", "Domain", "Mean", "SD", "SE")
domain.clas.df$Season <- c(rep("Summer", 4), rep("Winter", 4), rep("Spring", 4))
domain.clas.df$Season <- ordered(domain.clas.df$Season, levels=c("Summer", "Winter", "Spring"))
domain.clas.df$Domain <- c(rep(c("Archaea", "Bacteria", "Eukaryota", "Viruses"), 3))
domain.clas.df$Domain <- ordered(domain.clas.df$Domain, levels=c("Archaea", "Bacteria", "Eukaryota",
                                                                "Viruses"))
domain.clas.df$Mean <- as.numeric(c(domain.clas.sum[1,2:5], domain.clas.sum[2, 2:5],
                                    domain.clas.sum[3, 2:5]))
domain.clas.df$SD <- as.numeric(c(domain.clas.sum[1, 6:9], domain.clas.sum[2, 6:9],
                                  domain.clas.sum[3, 6:9]))
domain.clas.df$SE <- as.numeric(c(domain.clas.sum[1, 10:13], domain.clas.sum[2, 10:13],
                                  domain.clas.sum[3, 10:13]))

# Barplot for all sequences
ggplot(domain.df, aes(x=Domain, y=Mean, fill=Domain)) +
  geom_bar(stat="identity") +
  geom_errorbar(aes(ymax=Mean+SE, ymin=Mean-SE), width=0.25) +
  scale_y_continuous(limits=c(-0.5,60)) +
  facet_grid(Season ~ .) +
  scale_fill_brewer(palette="Set1") +
  xlab("Phyla") +
  ylab("Mean Relative Abundance") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(face="bold"),
        legend.title = element_text(face="bold"))

# Barplot for classified sequences
ggplot(domain.clas.df, aes(x=Domain, y=Mean, fill=Domain)) +
  geom_bar(stat="identity") +
  geom_errorbar(aes(ymax=Mean+SE, ymin=Mean-SE), width=0.25) +
  scale_y_continuous(limits=c(-0.5,100)) +
  facet_grid(Season ~ .) +
  scale_fill_brewer(palette="Set1") +
  xlab("Phyla") +
  ylab("Mean Relative Abundance") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(face="bold"),
        legend.title = element_text(face="bold"))



########## Phylum ##########
phy.sum <- import.phylum.sum('kaiju/nohost/phylum')
#write.csv(phy.sum, file = "kaiju/nohost/phy.sum.csv")

# Summarize phyla to get top 10
phy.sum.sum <- phy.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))
  # Top 10 phyla = Unclassified, Bacteroidetes, Firmicutes, Verrucomicrobia, Proteobacteria, Actinobacteria, Candidatus Melainabacteria, Spirochaetes, Tenericutes, Elusimicrobia (and Fusobacteria)




########## Class ##########
cla.sum <- import.class.sum('kaiju/nohost/class')
#write.csv(cla.sum, file = "kaiju/nohost/cla.sum.csv")

# Summarize classes to get top 10
cla.sum.sum <- cla.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.sum <- import.order.sum('kaiju/nohost/order')
#write.csv(ord.sum, file = "kaiju/nohost/ord.sum.csv")

# Summarize orders to get top 10
ord.sum.sum <- ord.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))




########## Family ##########
fam.sum <- import.family.sum('kaiju/nohost/family')
#write.csv(fam.sum, file = "kaiju/nohost/fam.sum.csv")

# Summarize families to get top 10
fam.sum.sum <- fam.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))




########## Genus ##########
gen.sum <- import.genus.sum('kaiju/nohost/genus')
#write.csv(gen.sum, file = "kaiju/nohost/gen.sum.csv")

# Summarize genera to get top 10
gen.sum.sum <- gen.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))




########## Species ##########
spe.sum <- import.species.sum('kaiju/nohost/species')
#write.csv(spe.sum, file = "kaiju/nohost/spe.sum.csv")

# Summarize genera to get top 10
spe.sum.sum <- spe.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


```

### All CAZymes
```{r}
########## Phylum ##########
phy.all.sum <- import.phylum.sum('kaiju/all_cazymes/phylum')
#write.csv(phy.all.sum, file = "kaiju/all_cazymes/phy.sum.csv")

# Summarize phyla to get top 10
phy.all.sum.sum <- phy.all.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.all.sum <- import.class.sum('kaiju/all_cazymes/class')
#write.csv(cla.all.sum, file = "kaiju/all_cazymes/cla.sum.csv")

# Summarize classes to get top 10
cla.all.sum.sum <- cla.all.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.all.sum <- import.order.sum('kaiju/all_cazymes/order')
#write.csv(ord.all.sum, file = "kaiju/all_cazymes/ord.sum.csv")

# Summarize orders to get top 10
ord.all.sum.sum <- ord.all.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.all.sum <- import.family.sum('kaiju/all_cazymes/family')
#write.csv(fam.all.sum, file = "kaiju/all_cazymes/fam.sum.csv")

# Summarize families to get top 10
fam.all.sum.sum <- fam.all.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))



########## Genus ##########
gen.all.sum <- import.genus.sum('kaiju/all_cazymes/genus')
#write.csv(gen.all.sum, file = "kaiju/all_cazymes/gen.sum.csv")

# Summarize genera to get top 10
gen.all.sum.sum <- gen.all.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))



########## Species ##########
spe.all.sum <- import.species.sum('kaiju/all_cazymes/species')
#write.csv(spe.all.sum, file = "kaiju/all_cazymes/spe.sum.csv")

# Summarize phyla to get top 10
spe.all.sum.sum <- spe.all.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))
```

### CE11
```{r}
########## Phylum ##########
phy.CE11.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/CE11/phylum')
#write.csv(phy.CE11.sum, file = "kaiju/sep_sig_cazymes/CE11/CE11.phy.sum.csv")

# Summarize phyla to get top 10
phy.CE11.sum.sum <- phy.CE11.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.CE11.sum <- import.class.sum('kaiju/sep_sig_cazymes/CE11/class')
#write.csv(cla.CE11.sum, file = "kaiju/sep_sig_cazymes/CE11/CE11.cla.sum.csv")

# Summarize classes to get top 10
cla.CE11.sum.sum <- cla.CE11.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.CE11.sum <- import.order.sum('kaiju/sep_sig_cazymes/CE11/order')
#write.csv(ord.CE11.sum, file = "kaiju/sep_sig_cazymes/CE11/CE11.ord.sum.csv")

# Summarize orders to get top 10
ord.CE11.sum.sum <- ord.CE11.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.CE11.sum <- import.family.sum('kaiju/sep_sig_cazymes/CE11/family')
#write.csv(fam.CE11.sum, file = "kaiju/sep_sig_cazymes/CE11/CE11.fam.sum.csv")

# Summarize families to get top 10
fam.CE11.sum.sum <- fam.CE11.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.CE11.sum <- import.genus.sum('kaiju/sep_sig_cazymes/CE11/genus')
#write.csv(gen.CE11.sum, file = "kaiju/sep_sig_cazymes/CE11/CE11.gen.sum.csv")

# Summarize genera to get top 10
gen.CE11.sum.sum <- gen.CE11.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.CE11.sum <- import.species.sum('kaiju/sep_sig_cazymes/CE11/species')
#write.csv(spe.CE11.sum, file = "kaiju/sep_sig_cazymes/CE11/CE11.spe.sum.csv")

# Summarize species to get top 10
spe.CE11.sum.sum <- spe.CE11.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### CE12
```{r}
########## Phylum ##########
phy.CE12.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/CE12/phylum')
#write.csv(phy.CE12.sum, file = "kaiju/sep_sig_cazymes/CE12/CE12.phy.sum.csv")

# Summarize phyla to get top 10
phy.CE12.sum.sum <- phy.CE12.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.CE12.sum <- import.class.sum('kaiju/sep_sig_cazymes/CE12/class')
#write.csv(cla.CE12.sum, file = "kaiju/sep_sig_cazymes/CE12/CE12.cla.sum.csv")

# Summarize classes to get top 10
cla.CE12.sum.sum <- cla.CE12.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.CE12.sum <- import.order.sum('kaiju/sep_sig_cazymes/CE12/order')
#write.csv(ord.CE12.sum, file = "kaiju/sep_sig_cazymes/CE12/CE12.ord.sum.csv")

# Summarize orders to get top 10
ord.CE12.sum.sum <- ord.CE12.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.CE12.sum <- import.family.sum('kaiju/sep_sig_cazymes/CE12/family')
#write.csv(fam.CE12.sum, file = "kaiju/sep_sig_cazymes/CE12/CE12.fam.sum.csv")

# Summarize families to get top 10
fam.CE12.sum.sum <- fam.CE12.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.CE12.sum <- import.genus.sum('kaiju/sep_sig_cazymes/CE12/genus')
#write.csv(gen.CE12.sum, file = "kaiju/sep_sig_cazymes/CE12/CE12.gen.sum.csv")

# Summarize genera to get top 10
gen.CE12.sum.sum <- gen.CE12.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.CE12.sum <- import.species.sum('kaiju/sep_sig_cazymes/CE12/species')
#write.csv(spe.CE12.sum, file = "kaiju/sep_sig_cazymes/CE12/CE12.spe.sum.csv")

# Summarize species to get top 10
spe.CE12.sum.sum <- spe.CE12.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH10
```{r}
########## Phylum ##########
phy.GH10.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GH10/phylum')
#write.csv(phy.GH10.sum, file = "kaiju/sep_sig_cazymes/GH10/GH10.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH10.sum.sum <- phy.GH10.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH10.sum <- import.class.sum('kaiju/sep_sig_cazymes/GH10/class')
#write.csv(cla.GH10.sum, file = "kaiju/sep_sig_cazymes/GH10/GH10.cla.sum.csv")

# Summarize classes to get top 10
cla.GH10.sum.sum <- cla.GH10.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH10.sum <- import.order.sum('kaiju/sep_sig_cazymes/GH10/order')
#write.csv(ord.GH10.sum, file = "kaiju/sep_sig_cazymes/GH10/GH10.ord.sum.csv")

# Summarize orders to get top 10
ord.GH10.sum.sum <- ord.GH10.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH10.sum <- import.family.sum('kaiju/sep_sig_cazymes/GH10/family')
#write.csv(fam.GH10.sum, file = "kaiju/sep_sig_cazymes/GH10/GH10.fam.sum.csv")

# Summarize families to get top 10
fam.GH10.sum.sum <- fam.GH10.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH10.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GH10/genus')
#write.csv(gen.GH10.sum, file = "kaiju/sep_sig_cazymes/GH10/GH10.gen.sum.csv")

# Summarize genera to get top 10
gen.GH10.sum.sum <- gen.GH10.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH10.sum <- import.species.sum('kaiju/sep_sig_cazymes/GH10/species')
#write.csv(spe.GH10.sum, file = "kaiju/sep_sig_cazymes/GH10/GH10.spe.sum.csv")

# Summarize species to get top 10
spe.GH10.sum.sum <- spe.GH10.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```



### GH106
```{r}
########## Phylum ##########
phy.GH106.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GH106/phylum')
#write.csv(phy.GH106.sum, file = "kaiju/sep_sig_cazymes/GH106/GH106.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH106.sum.sum <- phy.GH106.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH106.sum <- import.class.sum('kaiju/sep_sig_cazymes/GH106/class')
#write.csv(cla.GH106.sum, file = "kaiju/sep_sig_cazymes/GH106/GH106.cla.sum.csv")

# Summarize classes to get top 10
cla.GH106.sum.sum <- cla.GH106.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH106.sum <- import.order.sum('kaiju/sep_sig_cazymes/GH106/order')
#write.csv(ord.GH106.sum, file = "kaiju/sep_sig_cazymes/GH106/GH106.ord.sum.csv")

# Summarize orders to get top 10
ord.GH106.sum.sum <- ord.GH106.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH106.sum <- import.family.sum('kaiju/sep_sig_cazymes/GH106/family')
#write.csv(fam.GH106.sum, file = "kaiju/sep_sig_cazymes/GH106/GH106.fam.sum.csv")

# Summarize families to get top 10
fam.GH106.sum.sum <- fam.GH106.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH106.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GH106/genus')
#write.csv(gen.GH106.sum, file = "kaiju/sep_sig_cazymes/GH106/GH106.gen.sum.csv")

# Summarize genera to get top 10
gen.GH106.sum.sum <- gen.GH106.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH106.sum <- import.species.sum('kaiju/sep_sig_cazymes/GH106/species')
#write.csv(spe.GH106.sum, file = "kaiju/sep_sig_cazymes/GH106/GH106.spe.sum.csv")

# Summarize species to get top 10
spe.GH106.sum.sum <- spe.GH106.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH115
```{r}
########## Phylum ##########
phy.GH115.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GH115/phylum')
#write.csv(phy.GH115.sum, file = "kaiju/sep_sig_cazymes/GH115/GH115.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH115.sum.sum <- phy.GH115.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH115.sum <- import.class.sum('kaiju/sep_sig_cazymes/GH115/class')
#write.csv(cla.GH115.sum, file = "kaiju/sep_sig_cazymes/GH115/GH115.cla.sum.csv")

# Summarize classes to get top 10
cla.GH115.sum.sum <- cla.GH115.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH115.sum <- import.order.sum('kaiju/sep_sig_cazymes/GH115/order')
#write.csv(ord.GH115.sum, file = "kaiju/sep_sig_cazymes/GH115/GH115.ord.sum.csv")

# Summarize orders to get top 10
ord.GH115.sum.sum <- ord.GH115.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH115.sum <- import.family.sum('kaiju/sep_sig_cazymes/GH115/family')
#write.csv(fam.GH115.sum, file = "kaiju/sep_sig_cazymes/GH115/GH115.fam.sum.csv")

# Summarize families to get top 10
fam.GH115.sum.sum <- fam.GH115.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH115.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GH115/genus')
#write.csv(gen.GH115.sum, file = "kaiju/sep_sig_cazymes/GH115/GH115.gen.sum.csv")

# Summarize genera to get top 10
gen.GH115.sum.sum <- gen.GH115.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH115.sum <- import.species.sum('kaiju/sep_sig_cazymes/GH115/species')
#write.csv(spe.GH115.sum, file = "kaiju/sep_sig_cazymes/GH115/GH115.spe.sum.csv")

# Summarize species to get top 10
spe.GH115.sum.sum <- spe.GH115.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH20
```{r}
########## Phylum ##########
phy.GH20.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GH20/phylum')
#write.csv(phy.GH20.sum, file = "kaiju/sep_sig_cazymes/GH20/GH20.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH20.sum.sum <- phy.GH20.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH20.sum <- import.class.sum('kaiju/sep_sig_cazymes/GH20/class')
#write.csv(cla.GH20.sum, file = "kaiju/sep_sig_cazymes/GH20/GH20.cla.sum.csv")

# Summarize classes to get top 10
cla.GH20.sum.sum <- cla.GH20.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH20.sum <- import.order.sum('kaiju/sep_sig_cazymes/GH20/order')
#write.csv(ord.GH20.sum, file = "kaiju/sep_sig_cazymes/GH20/GH20.ord.sum.csv")

# Summarize orders to get top 10
ord.GH20.sum.sum <- ord.GH20.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH20.sum <- import.family.sum('kaiju/sep_sig_cazymes/GH20/family')
#write.csv(fam.GH20.sum, file = "kaiju/sep_sig_cazymes/GH20/GH20.fam.sum.csv")

# Summarize families to get top 10
fam.GH20.sum.sum <- fam.GH20.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH20.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GH20/genus')
#write.csv(gen.GH20.sum, file = "kaiju/sep_sig_cazymes/GH20/GH20.gen.sum.csv")

# Summarize genera to get top 10
gen.GH20.sum.sum <- gen.GH20.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))



########## Species ##########
spe.GH20.sum <- import.species.sum('kaiju/sep_sig_cazymes/GH20/species')
#write.csv(spe.GH20.sum, file = "kaiju/sep_sig_cazymes/GH20/GH20.spe.sum.csv")

# Summarize species to get top 10
spe.GH20.sum.sum <- spe.GH20.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH3
```{r}
########## Phylum ##########
phy.GH3.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GH3/phylum')
#write.csv(phy.GH3.sum, file = "kaiju/sep_sig_cazymes/GH3/GH3.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH3.sum.sum <- phy.GH3.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH3.sum <- import.class.sum('kaiju/sep_sig_cazymes/GH3/class')
#write.csv(cla.GH3.sum, file = "kaiju/sep_sig_cazymes/GH3/GH3.cla.sum.csv")

# Summarize classes to get top 10
cla.GH3.sum.sum <- cla.GH3.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH3.sum <- import.order.sum('kaiju/sep_sig_cazymes/GH3/order')
#write.csv(ord.GH3.sum, file = "kaiju/sep_sig_cazymes/GH3/GH3.ord.sum.csv")

# Summarize orders to get top 10
ord.GH3.sum.sum <- ord.GH3.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH3.sum <- import.family.sum('kaiju/sep_sig_cazymes/GH3/family')
#write.csv(fam.GH3.sum, file = "kaiju/sep_sig_cazymes/GH3/GH3.fam.sum.csv")

# Summarize families to get top 10
fam.GH3.sum.sum <- fam.GH3.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH3.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GH3/genus')
#write.csv(gen.GH3.sum, file = "kaiju/sep_sig_cazymes/GH3/GH3.gen.sum.csv")

# Summarize genera to get top 10
gen.GH3.sum.sum <- gen.GH3.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH3.sum <- import.species.sum('kaiju/sep_sig_cazymes/GH3/species')
#write.csv(spe.GH3.sum, file = "kaiju/sep_sig_cazymes/GH3/GH3.spe.sum.csv")

# Summarize species to get top 10
spe.GH3.sum.sum <- spe.GH3.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH32
```{r}
########## Phylum ##########
phy.GH32.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GH32/phylum')
#write.csv(phy.GH32.sum, file = "kaiju/sep_sig_cazymes/GH32/GH32.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH32.sum.sum <- phy.GH32.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH32.sum <- import.class.sum('kaiju/sep_sig_cazymes/GH32/class')
#write.csv(cla.GH32.sum, file = "kaiju/sep_sig_cazymes/GH32/GH32.cla.sum.csv")

# Summarize classes to get top 10
cla.GH32.sum.sum <- cla.GH32.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH32.sum <- import.order.sum('kaiju/sep_sig_cazymes/GH32/order')
#write.csv(ord.GH32.sum, file = "kaiju/sep_sig_cazymes/GH32/GH32.ord.sum.csv")

# Summarize orders to get top 10
ord.GH32.sum.sum <- ord.GH32.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH32.sum <- import.family.sum('kaiju/sep_sig_cazymes/GH32/family')
#write.csv(fam.GH32.sum, file = "kaiju/sep_sig_cazymes/GH32/GH32.fam.sum.csv")

# Summarize families to get top 10
fam.GH32.sum.sum <- fam.GH32.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH32.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GH32/genus')
#write.csv(gen.GH32.sum, file = "kaiju/sep_sig_cazymes/GH32/GH32.gen.sum.csv")

# Summarize genera to get top 10
gen.GH32.sum.sum <- gen.GH32.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH32.sum <- import.species.sum('kaiju/sep_sig_cazymes/GH32/species')
#write.csv(spe.GH32.sum, file = "kaiju/sep_sig_cazymes/GH32/GH32.spe.sum.csv")

# Summarize species to get top 10
spe.GH32.sum.sum <- spe.GH32.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH39
```{r}
########## Phylum ##########
phy.GH39.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GH39/phylum')
#write.csv(phy.GH39.sum, file = "kaiju/sep_sig_cazymes/GH39/GH39.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH39.sum.sum <- phy.GH39.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH39.sum <- import.class.sum('kaiju/sep_sig_cazymes/GH39/class')
#write.csv(cla.GH39.sum, file = "kaiju/sep_sig_cazymes/GH39/GH39.cla.sum.csv")

# Summarize classes to get top 10
cla.GH39.sum.sum <- cla.GH39.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH39.sum <- import.order.sum('kaiju/sep_sig_cazymes/GH39/order')
#write.csv(ord.GH39.sum, file = "kaiju/sep_sig_cazymes/GH39/GH39.ord.sum.csv")

# Summarize orders to get top 10
ord.GH39.sum.sum <- ord.GH39.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH39.sum <- import.family.sum('kaiju/sep_sig_cazymes/GH39/family')
#write.csv(fam.GH39.sum, file = "kaiju/sep_sig_cazymes/GH39/GH39.fam.sum.csv")

# Summarize families to get top 10
fam.GH39.sum.sum <- fam.GH39.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH39.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GH39/genus')
#write.csv(gen.GH39.sum, file = "kaiju/sep_sig_cazymes/GH39/GH39.gen.sum.csv")

# Summarize genera to get top 10
gen.GH39.sum.sum <- gen.GH39.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH39.sum <- import.species.sum('kaiju/sep_sig_cazymes/GH39/species')
#write.csv(spe.GH39.sum, file = "kaiju/sep_sig_cazymes/GH39/GH39.spe.sum.csv")

# Summarize species to get top 10
spe.GH39.sum.sum <- spe.GH39.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH42
```{r}
########## Phylum ##########
phy.GH42.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GH42/phylum')
#write.csv(phy.GH42.sum, file = "kaiju/sep_sig_cazymes/GH42/GH42.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH42.sum.sum <- phy.GH42.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH42.sum <- import.class.sum('kaiju/sep_sig_cazymes/GH42/class')
#write.csv(cla.GH42.sum, file = "kaiju/sep_sig_cazymes/GH42/GH42.cla.sum.csv")

# Summarize classes to get top 10
cla.GH42.sum.sum <- cla.GH42.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH42.sum <- import.order.sum('kaiju/sep_sig_cazymes/GH42/order')
#write.csv(ord.GH42.sum, file = "kaiju/sep_sig_cazymes/GH42/GH42.ord.sum.csv")

# Summarize orders to get top 10
ord.GH42.sum.sum <- ord.GH42.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH42.sum <- import.family.sum('kaiju/sep_sig_cazymes/GH42/family')
#write.csv(fam.GH42.sum, file = "kaiju/sep_sig_cazymes/GH42/GH42.fam.sum.csv")

# Summarize families to get top 10
fam.GH42.sum.sum <- fam.GH42.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH42.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GH42/genus')
#write.csv(gen.GH42.sum, file = "kaiju/sep_sig_cazymes/GH42/GH42.gen.sum.csv")

# Summarize genera to get top 10
gen.GH42.sum.sum <- gen.GH42.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH42.sum <- import.species.sum('kaiju/sep_sig_cazymes/GH42/species')
#write.csv(spe.GH42.sum, file = "kaiju/sep_sig_cazymes/GH42/GH42.spe.sum.csv")

# Summarize species to get top 10
spe.GH42.sum.sum <- spe.GH42.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH43
```{r}
########## Phylum ##########
phy.GH43.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GH43/phylum')
#write.csv(phy.GH43.sum, file = "kaiju/sep_sig_cazymes/GH43/GH43.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH43.sum.sum <- phy.GH43.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH43.sum <- import.class.sum('kaiju/sep_sig_cazymes/GH43/class')
#write.csv(cla.GH43.sum, file = "kaiju/sep_sig_cazymes/GH43/GH43.cla.sum.csv")

# Summarize classes to get top 10
cla.GH43.sum.sum <- cla.GH43.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH43.sum <- import.order.sum('kaiju/sep_sig_cazymes/GH43/order')
#write.csv(ord.GH43.sum, file = "kaiju/sep_sig_cazymes/GH43/GH43.ord.sum.csv")

# Summarize orders to get top 10
ord.GH43.sum.sum <- ord.GH43.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH43.sum <- import.family.sum('kaiju/sep_sig_cazymes/GH43/family')
#write.csv(fam.GH43.sum, file = "kaiju/sep_sig_cazymes/GH43/GH43.fam.sum.csv")

# Summarize families to get top 10
fam.GH43.sum.sum <- fam.GH43.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH43.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GH43/genus')
#write.csv(gen.GH43.sum, file = "kaiju/sep_sig_cazymes/GH43/GH43.gen.sum.csv")

# Summarize genera to get top 10
gen.GH43.sum.sum <- gen.GH43.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH43.sum <- import.species.sum('kaiju/sep_sig_cazymes/GH43/species')
#write.csv(spe.GH43.sum, file = "kaiju/sep_sig_cazymes/GH43/GH43.spe.sum.csv")

# Summarize species to get top 10
spe.GH43.sum.sum <- spe.GH43.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH5
```{r}
########## Phylum ##########
phy.GH5.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GH5/phylum')
#write.csv(phy.GH5.sum, file = "kaiju/sep_sig_cazymes/GH5/GH5.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH5.sum.sum <- phy.GH5.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH5.sum <- import.class.sum('kaiju/sep_sig_cazymes/GH5/class')
#write.csv(cla.GH5.sum, file = "kaiju/sep_sig_cazymes/GH5/GH5.cla.sum.csv")

# Summarize classes to get top 10
cla.GH5.sum.sum <- cla.GH5.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH5.sum <- import.order.sum('kaiju/sep_sig_cazymes/GH5/order')
#write.csv(ord.GH5.sum, file = "kaiju/sep_sig_cazymes/GH5/GH5.ord.sum.csv")

# Summarize orders to get top 10
ord.GH5.sum.sum <- ord.GH5.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH5.sum <- import.family.sum('kaiju/sep_sig_cazymes/GH5/family')
#write.csv(fam.GH5.sum, file = "kaiju/sep_sig_cazymes/GH5/GH5.fam.sum.csv")

# Summarize families to get top 10
fam.GH5.sum.sum <- fam.GH5.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH5.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GH5/genus')
#write.csv(gen.GH5.sum, file = "kaiju/sep_sig_cazymes/GH5/GH5.gen.sum.csv")

# Summarize genera to get top 10
gen.GH5.sum.sum <- gen.GH5.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH5.sum <- import.species.sum('kaiju/sep_sig_cazymes/GH5/species')
#write.csv(spe.GH5.sum, file = "kaiju/sep_sig_cazymes/GH5/GH5.spe.sum.csv")

# Summarize species to get top 10
spe.GH5.sum.sum <- spe.GH5.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### Kaiju - GH59 ###########################
```{r}
########## Phylum ##########
phy.GH59.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GH59/phylum')
write.csv(phy.GH59.sum, file = "kaiju/sep_sig_cazymes/GH59/GH59.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH59.sum.sum <- phy.GH59.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH59.sum <- import.class.sum('kaiju/sep_sig_cazymes/GH59/class')
write.csv(cla.GH59.sum, file = "kaiju/sep_sig_cazymes/GH59/GH59.cla.sum.csv")

# Summarize classes to get top 10
cla.GH59.sum.sum <- cla.GH59.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH59.sum <- import.order.sum('kaiju/sep_sig_cazymes/GH59/order')
write.csv(ord.GH59.sum, file = "kaiju/sep_sig_cazymes/GH59/GH59.ord.sum.csv")

# Summarize orders to get top 10
ord.GH59.sum.sum <- ord.GH59.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH59.sum <- import.family.sum('kaiju/sep_sig_cazymes/GH59/family')
write.csv(fam.GH59.sum, file = "kaiju/sep_sig_cazymes/GH59/GH59.fam.sum.csv")

# Summarize families to get top 10
fam.GH59.sum.sum <- fam.GH59.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH59.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GH59/genus')
write.csv(gen.GH59.sum, file = "kaiju/sep_sig_cazymes/GH59/GH59.gen.sum.csv")

# Summarize genera to get top 10
gen.GH59.sum.sum <- gen.GH59.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH59.sum <- import.species.sum('kaiju/sep_sig_cazymes/GH59/species')
write.csv(spe.GH59.sum, file = "kaiju/sep_sig_cazymes/GH59/GH59.spe.sum.csv")

# Summarize species to get top 10
spe.GH59.sum.sum <- spe.GH59.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH78
```{r}
########## Phylum ##########
phy.GH78.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GH78/phylum')
#write.csv(phy.GH78.sum, file = "kaiju/sep_sig_cazymes/GH78/GH78.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH78.sum.sum <- phy.GH78.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH78.sum <- import.class.sum('kaiju/sep_sig_cazymes/GH78/class')
#write.csv(cla.GH78.sum, file = "kaiju/sep_sig_cazymes/GH78/GH78.cla.sum.csv")

# Summarize classes to get top 10
cla.GH78.sum.sum <- cla.GH78.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH78.sum <- import.order.sum('kaiju/sep_sig_cazymes/GH78/order')
#write.csv(ord.GH78.sum, file = "kaiju/sep_sig_cazymes/GH78/GH78.ord.sum.csv")

# Summarize orders to get top 10
ord.GH78.sum.sum <- ord.GH78.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH78.sum <- import.family.sum('kaiju/sep_sig_cazymes/GH78/family')
#write.csv(fam.GH78.sum, file = "kaiju/sep_sig_cazymes/GH78/GH78.fam.sum.csv")

# Summarize families to get top 10
fam.GH78.sum.sum <- fam.GH78.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH78.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GH78/genus')
#write.csv(gen.GH78.sum, file = "kaiju/sep_sig_cazymes/GH78/GH78.gen.sum.csv")

# Summarize genera to get top 10
gen.GH78.sum.sum <- gen.GH78.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH78.sum <- import.species.sum('kaiju/sep_sig_cazymes/GH78/species')
#write.csv(spe.GH78.sum, file = "kaiju/sep_sig_cazymes/GH78/GH78.spe.sum.csv")

# Summarize species to get top 10
spe.GH78.sum.sum <- spe.GH78.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH84
```{r}
########## Phylum ##########
phy.GH84.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GH84/phylum')
#write.csv(phy.GH84.sum, file = "kaiju/sep_sig_cazymes/GH84/GH84.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH84.sum.sum <- phy.GH84.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH84.sum <- import.class.sum('kaiju/sep_sig_cazymes/GH84/class')
#write.csv(cla.GH84.sum, file = "kaiju/sep_sig_cazymes/GH84/GH84.cla.sum.csv")

# Summarize classes to get top 10
cla.GH84.sum.sum <- cla.GH84.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH84.sum <- import.order.sum('kaiju/sep_sig_cazymes/GH84/order')
#write.csv(ord.GH84.sum, file = "kaiju/sep_sig_cazymes/GH84/GH84.ord.sum.csv")

# Summarize orders to get top 10
ord.GH84.sum.sum <- ord.GH84.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH84.sum <- import.family.sum('kaiju/sep_sig_cazymes/GH84/family')
#write.csv(fam.GH84.sum, file = "kaiju/sep_sig_cazymes/GH84/GH84.fam.sum.csv")

# Summarize families to get top 10
fam.GH84.sum.sum <- fam.GH84.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH84.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GH84/genus')
#write.csv(gen.GH84.sum, file = "kaiju/sep_sig_cazymes/GH84/GH84.gen.sum.csv")

# Summarize genera to get top 10
gen.GH84.sum.sum <- gen.GH84.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH84.sum <- import.species.sum('kaiju/sep_sig_cazymes/GH84/species')
#write.csv(spe.GH84.sum, file = "kaiju/sep_sig_cazymes/GH84/GH84.spe.sum.csv")

# Summarize species to get top 10
spe.GH84.sum.sum <- spe.GH84.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```


### GT101
```{r}
########## Phylum ##########
phy.GT101.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GT101/phylum')
#write.csv(phy.GT101.sum, file = "kaiju/sep_sig_cazymes/GT101/GT101.phy.sum.csv")

# Summarize phyla to get top 10
phy.GT101.sum.sum <- phy.GT101.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GT101.sum <- import.class.sum('kaiju/sep_sig_cazymes/GT101/class')
#write.csv(cla.GT101.sum, file = "kaiju/sep_sig_cazymes/GT101/GT101.cla.sum.csv")

# Summarize classes to get top 10
cla.GT101.sum.sum <- cla.GT101.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GT101.sum <- import.order.sum('kaiju/sep_sig_cazymes/GT101/order')
#write.csv(ord.GT101.sum, file = "kaiju/sep_sig_cazymes/GT101/GT101.ord.sum.csv")

# Summarize orders to get top 10
ord.GT101.sum.sum <- ord.GT101.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GT101.sum <- import.family.sum('kaiju/sep_sig_cazymes/GT101/family')
#write.csv(fam.GT101.sum, file = "kaiju/sep_sig_cazymes/GT101/GT101.fam.sum.csv")

# Summarize families to get top 10
fam.GT101.sum.sum <- fam.GT101.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GT101.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GT101/genus')
#write.csv(gen.GT101.sum, file = "kaiju/sep_sig_cazymes/GT101/GT101.gen.sum.csv")

# Summarize genera to get top 10
gen.GT101.sum.sum <- gen.GT101.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GT101.sum <- import.species.sum('kaiju/sep_sig_cazymes/GT101/species')
#write.csv(spe.GT101.sum, file = "kaiju/sep_sig_cazymes/GT101/GT101.spe.sum.csv")

# Summarize species to get top 10
spe.GT101.sum.sum <- spe.GT101.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GT3
```{r}
########## Phylum ##########
phy.GT3.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GT3/phylum')
#write.csv(phy.GT3.sum, file = "kaiju/sep_sig_cazymes/GT3/GT3.phy.sum.csv")

# Summarize phyla to get top 10
phy.GT3.sum.sum <- phy.GT3.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GT3.sum <- import.class.sum('kaiju/sep_sig_cazymes/GT3/class')
#write.csv(cla.GT3.sum, file = "kaiju/sep_sig_cazymes/GT3/GT3.cla.sum.csv")

# Summarize classes to get top 10
cla.GT3.sum.sum <- cla.GT3.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GT3.sum <- import.order.sum('kaiju/sep_sig_cazymes/GT3/order')
#write.csv(ord.GT3.sum, file = "kaiju/sep_sig_cazymes/GT3/GT3.ord.sum.csv")

# Summarize orders to get top 10
ord.GT3.sum.sum <- ord.GT3.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GT3.sum <- import.family.sum('kaiju/sep_sig_cazymes/GT3/family')
#write.csv(fam.GT3.sum, file = "kaiju/sep_sig_cazymes/GT3/GT3.fam.sum.csv")

# Summarize families to get top 10
fam.GT3.sum.sum <- fam.GT3.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GT3.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GT3/genus')
#write.csv(gen.GT3.sum, file = "kaiju/sep_sig_cazymes/GT3/GT3.gen.sum.csv")

# Summarize genera to get top 10
gen.GT3.sum.sum <- gen.GT3.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GT3.sum <- import.species.sum('kaiju/sep_sig_cazymes/GT3/species')
#write.csv(spe.GT3.sum, file = "kaiju/sep_sig_cazymes/GT3/GT3.spe.sum.csv")

# Summarize species to get top 10
spe.GT3.sum.sum <- spe.GT3.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```








### GT4
```{r}
########## Phylum ##########
phy.GT4.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GT4/phylum')
#write.csv(phy.GT4.sum, file = "kaiju/sep_sig_cazymes/GT4/GT4.phy.sum.csv")

# Summarize phyla to get top 10
phy.GT4.sum.sum <- phy.GT4.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GT4.sum <- import.class.sum('kaiju/sep_sig_cazymes/GT4/class')
#write.csv(cla.GT4.sum, file = "kaiju/sep_sig_cazymes/GT4/GT4.cla.sum.csv")

# Summarize classes to get top 10
cla.GT4.sum.sum <- cla.GT4.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GT4.sum <- import.order.sum('kaiju/sep_sig_cazymes/GT4/order')
#write.csv(ord.GT4.sum, file = "kaiju/sep_sig_cazymes/GT4/GT4.ord.sum.csv")

# Summarize orders to get top 10
ord.GT4.sum.sum <- ord.GT4.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GT4.sum <- import.family.sum('kaiju/sep_sig_cazymes/GT4/family')
#write.csv(fam.GT4.sum, file = "kaiju/sep_sig_cazymes/GT4/GT4.fam.sum.csv")

# Summarize families to get top 10
fam.GT4.sum.sum <- fam.GT4.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GT4.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GT4/genus')
#write.csv(gen.GT4.sum, file = "kaiju/sep_sig_cazymes/GT4/GT4.gen.sum.csv")

# Summarize genera to get top 10
gen.GT4.sum.sum <- gen.GT4.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GT4.sum <- import.species.sum('kaiju/sep_sig_cazymes/GT4/species')
#write.csv(spe.GT4.sum, file = "kaiju/sep_sig_cazymes/GT4/GT4.spe.sum.csv")

# Summarize species to get top 10
spe.GT4.sum.sum <- spe.GT4.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GT41
```{r}
########## Phylum ##########
phy.GT41.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GT41/phylum')
#write.csv(phy.GT41.sum, file = "kaiju/sep_sig_cazymes/GT41/GT41.phy.sum.csv")

# Summarize phyla to get top 10
phy.GT41.sum.sum <- phy.GT41.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GT41.sum <- import.class.sum('kaiju/sep_sig_cazymes/GT41/class')
#write.csv(cla.GT41.sum, file = "kaiju/sep_sig_cazymes/GT41/GT41.cla.sum.csv")

# Summarize classes to get top 10
cla.GT41.sum.sum <- cla.GT41.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GT41.sum <- import.order.sum('kaiju/sep_sig_cazymes/GT41/order')
#write.csv(ord.GT41.sum, file = "kaiju/sep_sig_cazymes/GT41/GT41.ord.sum.csv")

# Summarize orders to get top 10
ord.GT41.sum.sum <- ord.GT41.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GT41.sum <- import.family.sum('kaiju/sep_sig_cazymes/GT41/family')
#write.csv(fam.GT41.sum, file = "kaiju/sep_sig_cazymes/GT41/GT41.fam.sum.csv")

# Summarize families to get top 10
fam.GT41.sum.sum <- fam.GT41.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GT41.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GT41/genus')
#write.csv(gen.GT41.sum, file = "kaiju/sep_sig_cazymes/GT41/GT41.gen.sum.csv")

# Summarize genera to get top 10
gen.GT41.sum.sum <- gen.GT41.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GT41.sum <- import.species.sum('kaiju/sep_sig_cazymes/GT41/species')
#write.csv(spe.GT41.sum, file = "kaiju/sep_sig_cazymes/GT41/GT41.spe.sum.csv")

# Summarize species to get top 10
spe.GT41.sum.sum <- spe.GT41.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GT9
```{r}
########## Phylum ##########
phy.GT9.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/GT9/phylum')
#write.csv(phy.GT9.sum, file = "kaiju/sep_sig_cazymes/GT9/GT9.phy.sum.csv")

# Summarize phyla to get top 10
phy.GT9.sum.sum <- phy.GT9.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GT9.sum <- import.class.sum('kaiju/sep_sig_cazymes/GT9/class')
#write.csv(cla.GT9.sum, file = "kaiju/sep_sig_cazymes/GT9/GT9.cla.sum.csv")

# Summarize classes to get top 10
cla.GT9.sum.sum <- cla.GT9.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GT9.sum <- import.order.sum('kaiju/sep_sig_cazymes/GT9/order')
#write.csv(ord.GT9.sum, file = "kaiju/sep_sig_cazymes/GT9/GT9.ord.sum.csv")

# Summarize orders to get top 10
ord.GT9.sum.sum <- ord.GT9.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GT9.sum <- import.family.sum('kaiju/sep_sig_cazymes/GT9/family')
#write.csv(fam.GT9.sum, file = "kaiju/sep_sig_cazymes/GT9/GT9.fam.sum.csv")

# Summarize families to get top 10
fam.GT9.sum.sum <- fam.GT9.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GT9.sum <- import.genus.sum('kaiju/sep_sig_cazymes/GT9/genus')
#write.csv(gen.GT9.sum, file = "kaiju/sep_sig_cazymes/GT9/GT9.gen.sum.csv")

# Summarize genera to get top 10
gen.GT9.sum.sum <- gen.GT9.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GT9.sum <- import.species.sum('kaiju/sep_sig_cazymes/GT9/species')
#write.csv(spe.GT9.sum, file = "kaiju/sep_sig_cazymes/GT9/GT9.spe.sum.csv")

# Summarize species to get top 10
spe.GT9.sum.sum <- spe.GT9.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### PL1
```{r}
########## Phylum ##########
phy.PL1.sum <- import.phylum.sum('kaiju/sep_sig_cazymes/PL1/phylum')
#write.csv(phy.PL1.sum, file = "kaiju/sep_sig_cazymes/PL1/PL1.phy.sum.csv")

# Summarize phyla to get top 10
phy.PL1.sum.sum <- phy.PL1.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.PL1.sum <- import.class.sum('kaiju/sep_sig_cazymes/PL1/class')
#write.csv(cla.PL1.sum, file = "kaiju/sep_sig_cazymes/PL1/PL1.cla.sum.csv")

# Summarize classes to get top 10
cla.PL1.sum.sum <- cla.PL1.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.PL1.sum <- import.order.sum('kaiju/sep_sig_cazymes/PL1/order')
#write.csv(ord.PL1.sum, file = "kaiju/sep_sig_cazymes/PL1/PL1.ord.sum.csv")

# Summarize orders to get top 10
ord.PL1.sum.sum <- ord.PL1.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.PL1.sum <- import.family.sum('kaiju/sep_sig_cazymes/PL1/family')
#write.csv(fam.PL1.sum, file = "kaiju/sep_sig_cazymes/PL1/PL1.fam.sum.csv")

# Summarize families to get top 10
fam.PL1.sum.sum <- fam.PL1.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.PL1.sum <- import.genus.sum('kaiju/sep_sig_cazymes/PL1/genus')
#write.csv(gen.PL1.sum, file = "kaiju/sep_sig_cazymes/PL1/PL1.gen.sum.csv")

# Summarize genera to get top 10
gen.PL1.sum.sum <- gen.PL1.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.PL1.sum <- import.species.sum('kaiju/sep_sig_cazymes/PL1/species')
#write.csv(spe.PL1.sum, file = "kaiju/sep_sig_cazymes/PL1/PL1.spe.sum.csv")

# Summarize species to get top 10
spe.PL1.sum.sum <- spe.PL1.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```







### Mucin All
```{r}
########## Phylum ##########
phy.muc.sum <- import.phylum.sum('kaiju/mucin_all/phylum')
#write.csv(phy.muc.sum, file = "kaiju/mucin_all/muc.phy.sum.csv")

# Summarize phyla to get top 10
phy.muc.sum.sum <- phy.muc.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.muc.sum <- import.class.sum('kaiju/mucin_all/class')
#write.csv(cla.muc.sum, file = "kaiju/mucin_all/muc.cla.sum.csv")

# Summarize classes to get top 10
cla.muc.sum.sum <- cla.muc.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.muc.sum <- import.order.sum('kaiju/mucin_all/order')
#write.csv(ord.muc.sum, file = "kaiju/mucin_all/muc.ord.sum.csv")

# Summarize orders to get top 10
ord.muc.sum.sum <- ord.muc.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.muc.sum <- import.family.sum('kaiju/mucin_all/family')
#write.csv(fam.muc.sum, file = "kaiju/mucin_all/muc.fam.sum.csv")

# Summarize families to get top 10
fam.muc.sum.sum <- fam.muc.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.muc.sum <- import.genus.sum('kaiju/mucin_all/genus')
#write.csv(gen.muc.sum, file = "kaiju/mucin_all/muc.gen.sum.csv")

# Summarize genera to get top 10
gen.muc.sum.sum <- gen.muc.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.muc.sum <- import.species.sum('kaiju/mucin_all/species')
#write.csv(spe.muc.sum, file = "kaiju/mucin_all/muc.spe.sum.csv")

# Summarize species to get top 10
spe.muc.sum.sum <- spe.muc.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```


### 4.1.3.3
```{r}
########## Phylum ##########
phy.4.1.3.3.sum <- import.phylum.sum('kaiju/mucin_sep/4.1.3.3/phylum')
#write.csv(phy.4.1.3.3.sum, file = "kaiju/mucin_sep/4.1.3.3/4.1.3.3.phy.sum.csv")

# Summarize phyla to get top 10
phy.4.1.3.3.sum.sum <- phy.4.1.3.3.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.4.1.3.3.sum <- import.class.sum('kaiju/mucin_sep/4.1.3.3/class')
#write.csv(cla.4.1.3.3.sum, file = "kaiju/mucin_sep/4.1.3.3/4.1.3.3.cla.sum.csv")

# Summarize classes to get top 10
cla.4.1.3.3.sum.sum <- cla.4.1.3.3.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.4.1.3.3.sum <- import.order.sum('kaiju/mucin_sep/4.1.3.3/order')
#write.csv(ord.4.1.3.3.sum, file = "kaiju/mucin_sep/4.1.3.3/4.1.3.3.ord.sum.csv")

# Summarize orders to get top 10
ord.4.1.3.3.sum.sum <- ord.4.1.3.3.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.4.1.3.3.sum <- import.family.sum('kaiju/mucin_sep/4.1.3.3/family')
#write.csv(fam.4.1.3.3.sum, file = "kaiju/mucin_sep/4.1.3.3/4.1.3.3.fam.sum.csv")

# Summarize families to get top 10
fam.4.1.3.3.sum.sum <- fam.4.1.3.3.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.4.1.3.3.sum <- import.genus.sum('kaiju/mucin_sep/4.1.3.3/genus')
#write.csv(gen.4.1.3.3.sum, file = "kaiju/mucin_sep/4.1.3.3/4.1.3.3.gen.sum.csv")

# Summarize genera to get top 10
gen.4.1.3.3.sum.sum <- gen.4.1.3.3.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.4.1.3.3.sum <- import.species.sum('kaiju/mucin_sep/4.1.3.3/species')
#write.csv(spe.4.1.3.3.sum, file = "kaiju/mucin_sep/4.1.3.3/4.1.3.3.spe.sum.csv")

# Summarize species to get top 10
spe.4.1.3.3.sum.sum <- spe.4.1.3.3.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```





### GH101_3.2.1.97 #####################
```{r}
########## Phylum ##########
phy.GH101_3.2.1.97.sum <- import.phylum.sum('kaiju/mucin_sep/GH101_3.2.1.97/phylum')
write.csv(phy.GH101_3.2.1.97.sum, file = "kaiju/mucin_sep/GH101_3.2.1.97/GH101_3.2.1.97.phy.sum.csv")

# Summarize phyla to get top 10
phy.muc.sum.sum <- phy.muc.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH101_3.2.1.97.sum <- import.class.sum('kaiju/mucin_sep/GH101_3.2.1.97/class')
write.csv(cla.GH101_3.2.1.97.sum, file = "kaiju/mucin_sep/GH101_3.2.1.97/GH101_3.2.1.97.cla.sum.csv")

# Summarize classes to get top 10
cla.muc.sum.sum <- cla.muc.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH101_3.2.1.97.sum <- import.order.sum('kaiju/mucin_sep/GH101_3.2.1.97/order')
write.csv(ord.GH101_3.2.1.97.sum, file = "kaiju/mucin_sep/GH101_3.2.1.97/GH101_3.2.1.97.ord.sum.csv")

# Summarize orders to get top 10
ord.muc.sum.sum <- ord.muc.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH101_3.2.1.97.sum <- import.family.sum('kaiju/mucin_sep/GH101_3.2.1.97/family')
write.csv(fam.GH101_3.2.1.97.sum, file = "kaiju/mucin_sep/GH101_3.2.1.97/GH101_3.2.1.97.fam.sum.csv")

# Summarize families to get top 10
fam.muc.sum.sum <- fam.muc.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH101_3.2.1.97.sum <- import.genus.sum('kaiju/mucin_sep/GH101_3.2.1.97/genus')
write.csv(gen.GH101_3.2.1.97.sum, file = "kaiju/mucin_sep/GH101_3.2.1.97/GH101_3.2.1.97.gen.sum.csv")

# Summarize genera to get top 10
gen.muc.sum.sum <- gen.muc.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH101_3.2.1.97.sum <- import.species.sum('kaiju/mucin_sep/GH101_3.2.1.97/species')
write.csv(spe.GH101_3.2.1.97.sum, file = "kaiju/mucin_sep/GH101_3.2.1.97/GH101_3.2.1.97.spe.sum.csv")

# Summarize species to get top 10
spe.muc.sum.sum <- spe.muc.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH110_3.2.1.22
```{r}
########## Phylum ##########
phy.GH110_3.2.1.22.sum <- import.phylum.sum('kaiju/mucin_sep/GH110_3.2.1.22/phylum')
#write.csv(phy.GH110_3.2.1.22.sum, file = "kaiju/mucin_sep/GH110_3.2.1.22/GH110_3.2.1.22.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH110_3.2.1.22.sum.sum <- phy.GH110_3.2.1.22.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH110_3.2.1.22.sum <- import.class.sum('kaiju/mucin_sep/GH110_3.2.1.22/class')
#write.csv(cla.GH110_3.2.1.22.sum, file = "kaiju/mucin_sep/GH110_3.2.1.22/GH110_3.2.1.22.cla.sum.csv")

# Summarize classes to get top 10
cla.GH110_3.2.1.22.sum.sum <- cla.GH110_3.2.1.22.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH110_3.2.1.22.sum <- import.order.sum('kaiju/mucin_sep/GH110_3.2.1.22/order')
#write.csv(ord.GH110_3.2.1.22.sum, file = "kaiju/mucin_sep/GH110_3.2.1.22/GH110_3.2.1.22.ord.sum.csv")

# Summarize orders to get top 10
ord.GH110_3.2.1.22.sum.sum <- ord.GH110_3.2.1.22.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH110_3.2.1.22.sum <- import.family.sum('kaiju/mucin_sep/GH110_3.2.1.22/family')
#write.csv(fam.GH110_3.2.1.22.sum, file = "kaiju/mucin_sep/GH110_3.2.1.22/GH110_3.2.1.22.fam.sum.csv")

# Summarize families to get top 10
fam.GH110_3.2.1.22.sum.sum <- fam.GH110_3.2.1.22.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH110_3.2.1.22.sum <- import.genus.sum('kaiju/mucin_sep/GH110_3.2.1.22/genus')
#write.csv(gen.GH110_3.2.1.22.sum, file = "kaiju/mucin_sep/GH110_3.2.1.22/GH110_3.2.1.22.gen.sum.csv")

# Summarize genera to get top 10
gen.GH110_3.2.1.22.sum.sum <- gen.GH110_3.2.1.22.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH110_3.2.1.22.sum <- import.species.sum('kaiju/mucin_sep/GH110_3.2.1.22/species')
#write.csv(spe.GH110_3.2.1.22.sum, file = "kaiju/mucin_sep/GH110_3.2.1.22/GH110_3.2.1.22.spe.sum.csv")

# Summarize species to get top 10
spe.GH110_3.2.1.22.sum.sum <- spe.GH110_3.2.1.22.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH112_2.4.1.211
```{r}
########## Phylum ##########
phy.GH112_2.4.1.211.sum <- import.phylum.sum('kaiju/mucin_sep/GH112_2.4.1.211/phylum')
#write.csv(phy.GH112_2.4.1.211.sum, file = "kaiju/mucin_sep/GH112_2.4.1.211/GH112_2.4.1.211.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH112_2.4.1.211.sum.sum <- phy.GH112_2.4.1.211.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH112_2.4.1.211.sum <- import.class.sum('kaiju/mucin_sep/GH112_2.4.1.211/class')
#write.csv(cla.GH112_2.4.1.211.sum, file = "kaiju/mucin_sep/GH112_2.4.1.211/GH112_2.4.1.211.cla.sum.csv")

# Summarize classes to get top 10
cla.GH112_2.4.1.211.sum.sum <- cla.GH112_2.4.1.211.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH112_2.4.1.211.sum <- import.order.sum('kaiju/mucin_sep/GH112_2.4.1.211/order')
#write.csv(ord.GH112_2.4.1.211.sum, file = "kaiju/mucin_sep/GH112_2.4.1.211/GH112_2.4.1.211.ord.sum.csv")

# Summarize orders to get top 10
ord.GH112_2.4.1.211.sum.sum <- ord.GH112_2.4.1.211.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH112_2.4.1.211.sum <- import.family.sum('kaiju/mucin_sep/GH112_2.4.1.211/family')
#write.csv(fam.GH112_2.4.1.211.sum, file = "kaiju/mucin_sep/GH112_2.4.1.211/GH112_2.4.1.211.fam.sum.csv")

# Summarize families to get top 10
fam.GH112_2.4.1.211.sum.sum <- fam.GH112_2.4.1.211.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH112_2.4.1.211.sum <- import.genus.sum('kaiju/mucin_sep/GH112_2.4.1.211/genus')
#write.csv(gen.GH112_2.4.1.211.sum, file = "kaiju/mucin_sep/GH112_2.4.1.211/GH112_2.4.1.211.gen.sum.csv")

# Summarize genera to get top 10
gen.GH112_2.4.1.211.sum.sum <- gen.GH112_2.4.1.211.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH112_2.4.1.211.sum <- import.species.sum('kaiju/mucin_sep/GH112_2.4.1.211/species')
#write.csv(spe.GH112_2.4.1.211.sum, file = "kaiju/mucin_sep/GH112_2.4.1.211/GH112_2.4.1.211.spe.sum.csv")

# Summarize species to get top 10
spe.GH112_2.4.1.211.sum.sum <- spe.GH112_2.4.1.211.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```



### GH130_2.4.1.281
```{r}
########## Phylum ##########
phy.GH130_2.4.1.281.sum <- import.phylum.sum('kaiju/mucin_sep/GH130_2.4.1.281/phylum')
#write.csv(phy.GH130_2.4.1.281.sum, file = "kaiju/mucin_sep/GH130_2.4.1.281/GH130_2.4.1.281.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH130_2.4.1.281.sum.sum <- phy.GH130_2.4.1.281.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH130_2.4.1.281.sum <- import.class.sum('kaiju/mucin_sep/GH130_2.4.1.281/class')
#write.csv(cla.GH130_2.4.1.281.sum, file = "kaiju/mucin_sep/GH130_2.4.1.281/GH130_2.4.1.281.cla.sum.csv")

# Summarize classes to get top 10
cla.GH130_2.4.1.281.sum.sum <- cla.GH130_2.4.1.281.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH130_2.4.1.281.sum <- import.order.sum('kaiju/mucin_sep/GH130_2.4.1.281/order')
#write.csv(ord.GH130_2.4.1.281.sum, file = "kaiju/mucin_sep/GH130_2.4.1.281/GH130_2.4.1.281.ord.sum.csv")

# Summarize orders to get top 10
ord.GH130_2.4.1.281.sum.sum <- ord.GH130_2.4.1.281.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH130_2.4.1.281.sum <- import.family.sum('kaiju/mucin_sep/GH130_2.4.1.281/family')
#write.csv(fam.GH130_2.4.1.281.sum, file = "kaiju/mucin_sep/GH130_2.4.1.281/GH130_2.4.1.281.fam.sum.csv")

# Summarize families to get top 10
fam.GH130_2.4.1.281.sum.sum <- fam.GH130_2.4.1.281.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH130_2.4.1.281.sum <- import.genus.sum('kaiju/mucin_sep/GH130_2.4.1.281/genus')
#write.csv(gen.GH130_2.4.1.281.sum, file = "kaiju/mucin_sep/GH130_2.4.1.281/GH130_2.4.1.281.gen.sum.csv")

# Summarize genera to get top 10
gen.GH130_2.4.1.281.sum.sum <- gen.GH130_2.4.1.281.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH130_2.4.1.281.sum <- import.species.sum('kaiju/mucin_sep/GH130_2.4.1.281/species')
#write.csv(spe.GH130_2.4.1.281.sum, file = "kaiju/mucin_sep/GH130_2.4.1.281/GH130_2.4.1.281.spe.sum.csv")

# Summarize species to get top 10
spe.GH130_2.4.1.281.sum.sum <- spe.GH130_2.4.1.281.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH130_2.4.1.320
```{r}
########## Phylum ##########
phy.GH130_2.4.1.320.sum <- import.phylum.sum('kaiju/mucin_sep/GH130_2.4.1.320/phylum')
#write.csv(phy.GH130_2.4.1.320.sum, file = "kaiju/mucin_sep/GH130_2.4.1.320/GH130_2.4.1.320.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH130_2.4.1.320.sum.sum <- phy.GH130_2.4.1.320.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH130_2.4.1.320.sum <- import.class.sum('kaiju/mucin_sep/GH130_2.4.1.320/class')
#write.csv(cla.GH130_2.4.1.320.sum, file = "kaiju/mucin_sep/GH130_2.4.1.320/GH130_2.4.1.320.cla.sum.csv")

# Summarize classes to get top 10
cla.GH130_2.4.1.320.sum.sum <- cla.GH130_2.4.1.320.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH130_2.4.1.320.sum <- import.order.sum('kaiju/mucin_sep/GH130_2.4.1.320/order')
#write.csv(ord.GH130_2.4.1.320.sum, file = "kaiju/mucin_sep/GH130_2.4.1.320/GH130_2.4.1.320.ord.sum.csv")

# Summarize orders to get top 10
ord.GH130_2.4.1.320.sum.sum <- ord.GH130_2.4.1.320.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH130_2.4.1.320.sum <- import.family.sum('kaiju/mucin_sep/GH130_2.4.1.320/family')
#write.csv(fam.GH130_2.4.1.320.sum, file = "kaiju/mucin_sep/GH130_2.4.1.320/GH130_2.4.1.320.fam.sum.csv")

# Summarize families to get top 10
fam.GH130_2.4.1.320.sum.sum <- fam.GH130_2.4.1.320.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH130_2.4.1.320.sum <- import.genus.sum('kaiju/mucin_sep/GH130_2.4.1.320/genus')
#write.csv(gen.GH130_2.4.1.320.sum, file = "kaiju/mucin_sep/GH130_2.4.1.320/GH130_2.4.1.320.gen.sum.csv")

# Summarize genera to get top 10
gen.GH130_2.4.1.320.sum.sum <- gen.GH130_2.4.1.320.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH130_2.4.1.320.sum <- import.species.sum('kaiju/mucin_sep/GH130_2.4.1.320/species')
#write.csv(spe.GH130_2.4.1.320.sum, file = "kaiju/mucin_sep/GH130_2.4.1.320/GH130_2.4.1.320.spe.sum.csv")

# Summarize species to get top 10
spe.GH130_2.4.1.320.sum.sum <- spe.GH130_2.4.1.320.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```


### GH20_3.2.1.52 #############
```{r}
########## Phylum ##########
phy.GH20_3.2.1.52.sum <- import.phylum.sum('kaiju/mucin_sep/GH20_3.2.1.52/phylum')
write.csv(phy.GH20_3.2.1.52.sum, file = "kaiju/mucin_sep/GH20_3.2.1.52/GH20_3.2.1.52.phy.sum.csv")

# Summarize phyla to get top 10
phy.muc.sum.sum <- phy.muc.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH20_3.2.1.52.sum <- import.class.sum('kaiju/mucin_sep/GH20_3.2.1.52/class')
write.csv(cla.GH20_3.2.1.52.sum, file = "kaiju/mucin_sep/GH20_3.2.1.52/GH20_3.2.1.52.cla.sum.csv")

# Summarize classes to get top 10
cla.muc.sum.sum <- cla.muc.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH20_3.2.1.52.sum <- import.order.sum('kaiju/mucin_sep/GH20_3.2.1.52/order')
write.csv(ord.GH20_3.2.1.52.sum, file = "kaiju/mucin_sep/GH20_3.2.1.52/GH20_3.2.1.52.ord.sum.csv")

# Summarize orders to get top 10
ord.muc.sum.sum <- ord.muc.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH20_3.2.1.52.sum <- import.family.sum('kaiju/mucin_sep/GH20_3.2.1.52/family')
write.csv(fam.GH20_3.2.1.52.sum, file = "kaiju/mucin_sep/GH20_3.2.1.52/GH20_3.2.1.52.fam.sum.csv")

# Summarize families to get top 10
fam.muc.sum.sum <- fam.muc.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH20_3.2.1.52.sum <- import.genus.sum('kaiju/mucin_sep/GH20_3.2.1.52/genus')
write.csv(gen.GH20_3.2.1.52.sum, file = "kaiju/mucin_sep/GH20_3.2.1.52/GH20_3.2.1.52.gen.sum.csv")

# Summarize genera to get top 10
gen.muc.sum.sum <- gen.muc.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH20_3.2.1.52.sum <- import.species.sum('kaiju/mucin_sep/GH20_3.2.1.52/species')
write.csv(spe.GH20_3.2.1.52.sum, file = "kaiju/mucin_sep/GH20_3.2.1.52/GH20_3.2.1.52.spe.sum.csv")

# Summarize species to get top 10
spe.muc.sum.sum <- spe.muc.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```


### GH27_3.2.1.22 
```{r}
########## Phylum ##########
phy.GH27_3.2.1.22.sum <- import.phylum.sum('kaiju/mucin_sep/GH27_3.2.1.22/phylum')
#write.csv(phy.GH27_3.2.1.22.sum, file = "kaiju/mucin_sep/GH27_3.2.1.22/GH27_3.2.1.22.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH27_3.2.1.22.sum.sum <- phy.GH27_3.2.1.22.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH27_3.2.1.22.sum <- import.class.sum('kaiju/mucin_sep/GH27_3.2.1.22/class')
#write.csv(cla.GH27_3.2.1.22.sum, file = "kaiju/mucin_sep/GH27_3.2.1.22/GH27_3.2.1.22.cla.sum.csv")

# Summarize classes to get top 10
cla.GH27_3.2.1.22.sum.sum <- cla.GH27_3.2.1.22.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH27_3.2.1.22.sum <- import.order.sum('kaiju/mucin_sep/GH27_3.2.1.22/order')
#write.csv(ord.GH27_3.2.1.22.sum, file = "kaiju/mucin_sep/GH27_3.2.1.22/GH27_3.2.1.22.ord.sum.csv")

# Summarize orders to get top 10
ord.GH27_3.2.1.22.sum.sum <- ord.GH27_3.2.1.22.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH27_3.2.1.22.sum <- import.family.sum('kaiju/mucin_sep/GH27_3.2.1.22/family')
#write.csv(fam.GH27_3.2.1.22.sum, file = "kaiju/mucin_sep/GH27_3.2.1.22/GH27_3.2.1.22.fam.sum.csv")

# Summarize families to get top 10
fam.GH27_3.2.1.22.sum.sum <- fam.GH27_3.2.1.22.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH27_3.2.1.22.sum <- import.genus.sum('kaiju/mucin_sep/GH27_3.2.1.22/genus')
#write.csv(gen.GH27_3.2.1.22.sum, file = "kaiju/mucin_sep/GH27_3.2.1.22/GH27_3.2.1.22.gen.sum.csv")

# Summarize genera to get top 10
gen.GH27_3.2.1.22.sum.sum <- gen.GH27_3.2.1.22.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH27_3.2.1.22.sum <- import.species.sum('kaiju/mucin_sep/GH27_3.2.1.22/species')
#write.csv(spe.GH27_3.2.1.22.sum, file = "kaiju/mucin_sep/GH27_3.2.1.22/GH27_3.2.1.22.spe.sum.csv")

# Summarize species to get top 10
spe.GH27_3.2.1.22.sum.sum <- spe.GH27_3.2.1.22.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```


### GH29_3.2.1.51 
```{r}
########## Phylum ##########
phy.GH29_3.2.1.51.sum <- import.phylum.sum('kaiju/mucin_sep/GH29_3.2.1.51/phylum')
#write.csv(phy.GH29_3.2.1.51.sum, file = "kaiju/mucin_sep/GH29_3.2.1.51/GH29_3.2.1.51.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH29_3.2.1.51.sum.sum <- phy.GH29_3.2.1.51.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH29_3.2.1.51.sum <- import.class.sum('kaiju/mucin_sep/GH29_3.2.1.51/class')
#write.csv(cla.GH29_3.2.1.51.sum, file = "kaiju/mucin_sep/GH29_3.2.1.51/GH29_3.2.1.51.cla.sum.csv")

# Summarize classes to get top 10
cla.GH29_3.2.1.51.sum.sum <- cla.GH29_3.2.1.51.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH29_3.2.1.51.sum <- import.order.sum('kaiju/mucin_sep/GH29_3.2.1.51/order')
#write.csv(ord.GH29_3.2.1.51.sum, file = "kaiju/mucin_sep/GH29_3.2.1.51/GH29_3.2.1.51.ord.sum.csv")

# Summarize orders to get top 10
ord.GH29_3.2.1.51.sum.sum <- ord.GH29_3.2.1.51.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH29_3.2.1.51.sum <- import.family.sum('kaiju/mucin_sep/GH29_3.2.1.51/family')
#write.csv(fam.GH29_3.2.1.51.sum, file = "kaiju/mucin_sep/GH29_3.2.1.51/GH29_3.2.1.51.fam.sum.csv")

# Summarize families to get top 10
fam.GH29_3.2.1.51.sum.sum <- fam.GH29_3.2.1.51.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH29_3.2.1.51.sum <- import.genus.sum('kaiju/mucin_sep/GH29_3.2.1.51/genus')
#write.csv(gen.GH29_3.2.1.51.sum, file = "kaiju/mucin_sep/GH29_3.2.1.51/GH29_3.2.1.51.gen.sum.csv")

# Summarize genera to get top 10
gen.GH29_3.2.1.51.sum.sum <- gen.GH29_3.2.1.51.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH29_3.2.1.51.sum <- import.species.sum('kaiju/mucin_sep/GH29_3.2.1.51/species')
#write.csv(spe.GH29_3.2.1.51.sum, file = "kaiju/mucin_sep/GH29_3.2.1.51/GH29_3.2.1.51.spe.sum.csv")

# Summarize species to get top 10
spe.GH29_3.2.1.51.sum.sum <- spe.GH29_3.2.1.51.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```


### GH2_3.2.1.23 
```{r}
########## Phylum ##########
phy.GH2_3.2.1.23.sum <- import.phylum.sum('kaiju/mucin_sep/GH2_3.2.1.23/phylum')
#write.csv(phy.GH2_3.2.1.23.sum, file = "kaiju/mucin_sep/GH2_3.2.1.23/GH2_3.2.1.23.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH2_3.2.1.23.sum.sum <- phy.GH2_3.2.1.23.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH2_3.2.1.23.sum <- import.class.sum('kaiju/mucin_sep/GH2_3.2.1.23/class')
#write.csv(cla.GH2_3.2.1.23.sum, file = "kaiju/mucin_sep/GH2_3.2.1.23/GH2_3.2.1.23.cla.sum.csv")

# Summarize classes to get top 10
cla.GH2_3.2.1.23.sum.sum <- cla.GH2_3.2.1.23.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH2_3.2.1.23.sum <- import.order.sum('kaiju/mucin_sep/GH2_3.2.1.23/order')
#write.csv(ord.GH2_3.2.1.23.sum, file = "kaiju/mucin_sep/GH2_3.2.1.23/GH2_3.2.1.23.ord.sum.csv")

# Summarize orders to get top 10
ord.GH2_3.2.1.23.sum.sum <- ord.GH2_3.2.1.23.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH2_3.2.1.23.sum <- import.family.sum('kaiju/mucin_sep/GH2_3.2.1.23/family')
#write.csv(fam.GH2_3.2.1.23.sum, file = "kaiju/mucin_sep/GH2_3.2.1.23/GH2_3.2.1.23.fam.sum.csv")

# Summarize families to get top 10
fam.GH2_3.2.1.23.sum.sum <- fam.GH2_3.2.1.23.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH2_3.2.1.23.sum <- import.genus.sum('kaiju/mucin_sep/GH2_3.2.1.23/genus')
#write.csv(gen.GH2_3.2.1.23.sum, file = "kaiju/mucin_sep/GH2_3.2.1.23/GH2_3.2.1.23.gen.sum.csv")

# Summarize genera to get top 10
gen.GH2_3.2.1.23.sum.sum <- gen.GH2_3.2.1.23.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH2_3.2.1.23.sum <- import.species.sum('kaiju/mucin_sep/GH2_3.2.1.23/species')
#write.csv(spe.GH2_3.2.1.23.sum, file = "kaiju/mucin_sep/GH2_3.2.1.23/GH2_3.2.1.23.spe.sum.csv")

# Summarize species to get top 10
spe.GH2_3.2.1.23.sum.sum <- spe.GH2_3.2.1.23.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```


### GH2_3.2.1.25 
```{r}
########## Phylum ##########
phy.GH2_3.2.1.25.sum <- import.phylum.sum('kaiju/mucin_sep/GH2_3.2.1.25/phylum')
#write.csv(phy.GH2_3.2.1.25.sum, file = "kaiju/mucin_sep/GH2_3.2.1.25/GH2_3.2.1.25.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH2_3.2.1.25.sum.sum <- phy.GH2_3.2.1.25.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH2_3.2.1.25.sum <- import.class.sum('kaiju/mucin_sep/GH2_3.2.1.25/class')
#write.csv(cla.GH2_3.2.1.25.sum, file = "kaiju/mucin_sep/GH2_3.2.1.25/GH2_3.2.1.25.cla.sum.csv")

# Summarize classes to get top 10
cla.GH2_3.2.1.25.sum.sum <- cla.GH2_3.2.1.25.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH2_3.2.1.25.sum <- import.order.sum('kaiju/mucin_sep/GH2_3.2.1.25/order')
#write.csv(ord.GH2_3.2.1.25.sum, file = "kaiju/mucin_sep/GH2_3.2.1.25/GH2_3.2.1.25.ord.sum.csv")

# Summarize orders to get top 10
ord.GH2_3.2.1.25.sum.sum <- ord.GH2_3.2.1.25.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH2_3.2.1.25.sum <- import.family.sum('kaiju/mucin_sep/GH2_3.2.1.25/family')
#write.csv(fam.GH2_3.2.1.25.sum, file = "kaiju/mucin_sep/GH2_3.2.1.25/GH2_3.2.1.25.fam.sum.csv")

# Summarize families to get top 10
fam.GH2_3.2.1.25.sum.sum <- fam.GH2_3.2.1.25.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH2_3.2.1.25.sum <- import.genus.sum('kaiju/mucin_sep/GH2_3.2.1.25/genus')
#write.csv(gen.GH2_3.2.1.25.sum, file = "kaiju/mucin_sep/GH2_3.2.1.25/GH2_3.2.1.25.gen.sum.csv")

# Summarize genera to get top 10
gen.GH2_3.2.1.25.sum.sum <- gen.GH2_3.2.1.25.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH2_3.2.1.25.sum <- import.species.sum('kaiju/mucin_sep/GH2_3.2.1.25/species')
#write.csv(spe.GH2_3.2.1.25.sum, file = "kaiju/mucin_sep/GH2_3.2.1.25/GH2_3.2.1.25.spe.sum.csv")

# Summarize species to get top 10
spe.GH2_3.2.1.25.sum.sum <- spe.GH2_3.2.1.25.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```


### GH31_3.2.1.20 
```{r}
########## Phylum ##########
phy.GH31_3.2.1.20.sum <- import.phylum.sum('kaiju/mucin_sep/GH31_3.2.1.20/phylum')
#write.csv(phy.GH31_3.2.1.20.sum, file = "kaiju/mucin_sep/GH31_3.2.1.20/GH31_3.2.1.20.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH31_3.2.1.20.sum.sum <- phy.GH31_3.2.1.20.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH31_3.2.1.20.sum <- import.class.sum('kaiju/mucin_sep/GH31_3.2.1.20/class')
#write.csv(cla.GH31_3.2.1.20.sum, file = "kaiju/mucin_sep/GH31_3.2.1.20/GH31_3.2.1.20.cla.sum.csv")

# Summarize classes to get top 10
cla.GH31_3.2.1.20.sum.sum <- cla.GH31_3.2.1.20.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH31_3.2.1.20.sum <- import.order.sum('kaiju/mucin_sep/GH31_3.2.1.20/order')
#write.csv(ord.GH31_3.2.1.20.sum, file = "kaiju/mucin_sep/GH31_3.2.1.20/GH31_3.2.1.20.ord.sum.csv")

# Summarize orders to get top 10
ord.GH31_3.2.1.20.sum.sum <- ord.GH31_3.2.1.20.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH31_3.2.1.20.sum <- import.family.sum('kaiju/mucin_sep/GH31_3.2.1.20/family')
#write.csv(fam.GH31_3.2.1.20.sum, file = "kaiju/mucin_sep/GH31_3.2.1.20/GH31_3.2.1.20.fam.sum.csv")

# Summarize families to get top 10
fam.GH31_3.2.1.20.sum.sum <- fam.GH31_3.2.1.20.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH31_3.2.1.20.sum <- import.genus.sum('kaiju/mucin_sep/GH31_3.2.1.20/genus')
#write.csv(gen.GH31_3.2.1.20.sum, file = "kaiju/mucin_sep/GH31_3.2.1.20/GH31_3.2.1.20.gen.sum.csv")

# Summarize genera to get top 10
gen.GH31_3.2.1.20.sum.sum <- gen.GH31_3.2.1.20.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH31_3.2.1.20.sum <- import.species.sum('kaiju/mucin_sep/GH31_3.2.1.20/species')
#write.csv(spe.GH31_3.2.1.20.sum, file = "kaiju/mucin_sep/GH31_3.2.1.20/GH31_3.2.1.20.spe.sum.csv")

# Summarize species to get top 10
spe.GH31_3.2.1.20.sum.sum <- spe.GH31_3.2.1.20.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```


### GH35_3.2.1.23 
```{r}
########## Phylum ##########
phy.GH35_3.2.1.23.sum <- import.phylum.sum('kaiju/mucin_sep/GH35_3.2.1.23/phylum')
#write.csv(phy.GH35_3.2.1.23.sum, file = "kaiju/mucin_sep/GH35_3.2.1.23/GH35_3.2.1.23.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH35_3.2.1.23.sum.sum <- phy.GH35_3.2.1.23.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH35_3.2.1.23.sum <- import.class.sum('kaiju/mucin_sep/GH35_3.2.1.23/class')
#write.csv(cla.GH35_3.2.1.23.sum, file = "kaiju/mucin_sep/GH35_3.2.1.23/GH35_3.2.1.23.cla.sum.csv")

# Summarize classes to get top 10
cla.GH35_3.2.1.23.sum.sum <- cla.GH35_3.2.1.23.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH35_3.2.1.23.sum <- import.order.sum('kaiju/mucin_sep/GH35_3.2.1.23/order')
#write.csv(ord.GH35_3.2.1.23.sum, file = "kaiju/mucin_sep/GH35_3.2.1.23/GH35_3.2.1.23.ord.sum.csv")

# Summarize orders to get top 10
ord.GH35_3.2.1.23.sum.sum <- ord.GH35_3.2.1.23.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH35_3.2.1.23.sum <- import.family.sum('kaiju/mucin_sep/GH35_3.2.1.23/family')
#write.csv(fam.GH35_3.2.1.23.sum, file = "kaiju/mucin_sep/GH35_3.2.1.23/GH35_3.2.1.23.fam.sum.csv")

# Summarize families to get top 10
fam.GH35_3.2.1.23.sum.sum <- fam.GH35_3.2.1.23.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH35_3.2.1.23.sum <- import.genus.sum('kaiju/mucin_sep/GH35_3.2.1.23/genus')
#write.csv(gen.GH35_3.2.1.23.sum, file = "kaiju/mucin_sep/GH35_3.2.1.23/GH35_3.2.1.23.gen.sum.csv")

# Summarize genera to get top 10
gen.GH35_3.2.1.23.sum.sum <- gen.GH35_3.2.1.23.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH35_3.2.1.23.sum <- import.species.sum('kaiju/mucin_sep/GH35_3.2.1.23/species')
#write.csv(spe.GH35_3.2.1.23.sum, file = "kaiju/mucin_sep/GH35_3.2.1.23/GH35_3.2.1.23.spe.sum.csv")

# Summarize species to get top 10
spe.GH35_3.2.1.23.sum.sum <- spe.GH35_3.2.1.23.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH36_3.2.1.22 
```{r}
########## Phylum ##########
phy.GH36_3.2.1.22.sum <- import.phylum.sum('kaiju/mucin_sep/GH36_3.2.1.22/phylum')
#write.csv(phy.GH36_3.2.1.22.sum, file = "kaiju/mucin_sep/GH36_3.2.1.22/GH36_3.2.1.22.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH36_3.2.1.22.sum.sum <- phy.GH36_3.2.1.22.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH36_3.2.1.22.sum <- import.class.sum('kaiju/mucin_sep/GH36_3.2.1.22/class')
#write.csv(cla.GH36_3.2.1.22.sum, file = "kaiju/mucin_sep/GH36_3.2.1.22/GH36_3.2.1.22.cla.sum.csv")

# Summarize classes to get top 10
cla.GH36_3.2.1.22.sum.sum <- cla.GH36_3.2.1.22.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH36_3.2.1.22.sum <- import.order.sum('kaiju/mucin_sep/GH36_3.2.1.22/order')
#write.csv(ord.GH36_3.2.1.22.sum, file = "kaiju/mucin_sep/GH36_3.2.1.22/GH36_3.2.1.22.ord.sum.csv")

# Summarize orders to get top 10
ord.GH36_3.2.1.22.sum.sum <- ord.GH36_3.2.1.22.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH36_3.2.1.22.sum <- import.family.sum('kaiju/mucin_sep/GH36_3.2.1.22/family')
#write.csv(fam.GH36_3.2.1.22.sum, file = "kaiju/mucin_sep/GH36_3.2.1.22/GH36_3.2.1.22.fam.sum.csv")

# Summarize families to get top 10
fam.GH36_3.2.1.22.sum.sum <- fam.GH36_3.2.1.22.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH36_3.2.1.22.sum <- import.genus.sum('kaiju/mucin_sep/GH36_3.2.1.22/genus')
#write.csv(gen.GH36_3.2.1.22.sum, file = "kaiju/mucin_sep/GH36_3.2.1.22/GH36_3.2.1.22.gen.sum.csv")

# Summarize genera to get top 10
gen.GH36_3.2.1.22.sum.sum <- gen.GH36_3.2.1.22.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH36_3.2.1.22.sum <- import.species.sum('kaiju/mucin_sep/GH36_3.2.1.22/species')
#write.csv(spe.GH36_3.2.1.22.sum, file = "kaiju/mucin_sep/GH36_3.2.1.22/GH36_3.2.1.22.spe.sum.csv")

# Summarize species to get top 10
spe.GH36_3.2.1.22.sum.sum <- spe.GH36_3.2.1.22.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH38_3.2.1.24 #############
```{r}
########## Phylum ##########
phy.GH38_3.2.1.24.sum <- import.phylum.sum('kaiju/mucin_sep/GH38_3.2.1.24/phylum')
write.csv(phy.GH38_3.2.1.24.sum, file = "kaiju/mucin_sep/GH38_3.2.1.24/GH38_3.2.1.24.phy.sum.csv")

# Summarize phyla to get top 10
phy.muc.sum.sum <- phy.muc.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH38_3.2.1.24.sum <- import.class.sum('kaiju/mucin_sep/GH38_3.2.1.24/class')
write.csv(cla.GH38_3.2.1.24.sum, file = "kaiju/mucin_sep/GH38_3.2.1.24/GH38_3.2.1.24.cla.sum.csv")

# Summarize classes to get top 10
cla.muc.sum.sum <- cla.muc.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH38_3.2.1.24.sum <- import.order.sum('kaiju/mucin_sep/GH38_3.2.1.24/order')
write.csv(ord.GH38_3.2.1.24.sum, file = "kaiju/mucin_sep/GH38_3.2.1.24/GH38_3.2.1.24.ord.sum.csv")

# Summarize orders to get top 10
ord.muc.sum.sum <- ord.muc.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH38_3.2.1.24.sum <- import.family.sum('kaiju/mucin_sep/GH38_3.2.1.24/family')
write.csv(fam.GH38_3.2.1.24.sum, file = "kaiju/mucin_sep/GH38_3.2.1.24/GH38_3.2.1.24.fam.sum.csv")

# Summarize families to get top 10
fam.muc.sum.sum <- fam.muc.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH38_3.2.1.24.sum <- import.genus.sum('kaiju/mucin_sep/GH38_3.2.1.24/genus')
write.csv(gen.GH38_3.2.1.24.sum, file = "kaiju/mucin_sep/GH38_3.2.1.24/GH38_3.2.1.24.gen.sum.csv")

# Summarize genera to get top 10
gen.muc.sum.sum <- gen.muc.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH38_3.2.1.24.sum <- import.species.sum('kaiju/mucin_sep/GH38_3.2.1.24/species')
write.csv(spe.GH38_3.2.1.24.sum, file = "kaiju/mucin_sep/GH38_3.2.1.24/GH38_3.2.1.24.spe.sum.csv")

# Summarize species to get top 10
spe.muc.sum.sum <- spe.muc.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```







### GH3_3.2.1.52 ################
```{r}
########## Phylum ##########
phy.GH3_3.2.1.52.sum <- import.phylum.sum('kaiju/mucin_sep/GH3_3.2.1.52/phylum')
write.csv(phy.GH3_3.2.1.52.sum, file = "kaiju/mucin_sep/GH3_3.2.1.52/GH3_3.2.1.52.phy.sum.csv")

# Summarize phyla to get top 10
phy.muc.sum.sum <- phy.muc.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH3_3.2.1.52.sum <- import.class.sum('kaiju/mucin_sep/GH3_3.2.1.52/class')
write.csv(cla.GH3_3.2.1.52.sum, file = "kaiju/mucin_sep/GH3_3.2.1.52/GH3_3.2.1.52.cla.sum.csv")

# Summarize classes to get top 10
cla.muc.sum.sum <- cla.muc.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH3_3.2.1.52.sum <- import.order.sum('kaiju/mucin_sep/GH3_3.2.1.52/order')
write.csv(ord.GH3_3.2.1.52.sum, file = "kaiju/mucin_sep/GH3_3.2.1.52/GH3_3.2.1.52.ord.sum.csv")

# Summarize orders to get top 10
ord.muc.sum.sum <- ord.muc.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH3_3.2.1.52.sum <- import.family.sum('kaiju/mucin_sep/GH3_3.2.1.52/family')
write.csv(fam.GH3_3.2.1.52.sum, file = "kaiju/mucin_sep/GH3_3.2.1.52/GH3_3.2.1.52.fam.sum.csv")

# Summarize families to get top 10
fam.muc.sum.sum <- fam.muc.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH3_3.2.1.52.sum <- import.genus.sum('kaiju/mucin_sep/GH3_3.2.1.52/genus')
write.csv(gen.GH3_3.2.1.52.sum, file = "kaiju/mucin_sep/GH3_3.2.1.52/GH3_3.2.1.52.gen.sum.csv")

# Summarize genera to get top 10
gen.muc.sum.sum <- gen.muc.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH3_3.2.1.52.sum <- import.species.sum('kaiju/mucin_sep/GH3_3.2.1.52/species')
write.csv(spe.GH3_3.2.1.52.sum, file = "kaiju/mucin_sep/GH3_3.2.1.52/GH3_3.2.1.52.spe.sum.csv")

# Summarize species to get top 10
spe.muc.sum.sum <- spe.muc.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

### GH42_3.2.1.23
```{r}
########## Phylum ##########
phy.GH42_3.2.1.23.sum <- import.phylum.sum('kaiju/mucin_sep/GH42_3.2.1.23/phylum')
#write.csv(phy.GH42_3.2.1.23.sum, file = "kaiju/mucin_sep/GH42_3.2.1.23/GH42_3.2.1.23.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH42_3.2.1.23.sum.sum <- phy.GH42_3.2.1.23.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH42_3.2.1.23.sum <- import.class.sum('kaiju/mucin_sep/GH42_3.2.1.23/class')
#write.csv(cla.GH42_3.2.1.23.sum, file = "kaiju/mucin_sep/GH42_3.2.1.23/GH42_3.2.1.23.cla.sum.csv")

# Summarize classes to get top 10
cla.GH42_3.2.1.23.sum.sum <- cla.GH42_3.2.1.23.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH42_3.2.1.23.sum <- import.order.sum('kaiju/mucin_sep/GH42_3.2.1.23/order')
#write.csv(ord.GH42_3.2.1.23.sum, file = "kaiju/mucin_sep/GH42_3.2.1.23/GH42_3.2.1.23.ord.sum.csv")

# Summarize orders to get top 10
ord.GH42_3.2.1.23.sum.sum <- ord.GH42_3.2.1.23.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH42_3.2.1.23.sum <- import.family.sum('kaiju/mucin_sep/GH42_3.2.1.23/family')
#write.csv(fam.GH42_3.2.1.23.sum, file = "kaiju/mucin_sep/GH42_3.2.1.23/GH42_3.2.1.23.fam.sum.csv")

# Summarize families to get top 10
fam.GH42_3.2.1.23.sum.sum <- fam.GH42_3.2.1.23.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH42_3.2.1.23.sum <- import.genus.sum('kaiju/mucin_sep/GH42_3.2.1.23/genus')
#write.csv(gen.GH42_3.2.1.23.sum, file = "kaiju/mucin_sep/GH42_3.2.1.23/GH42_3.2.1.23.gen.sum.csv")

# Summarize genera to get top 10
gen.GH42_3.2.1.23.sum.sum <- gen.GH42_3.2.1.23.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH42_3.2.1.23.sum <- import.species.sum('kaiju/mucin_sep/GH42_3.2.1.23/species')
#write.csv(spe.GH42_3.2.1.23.sum, file = "kaiju/mucin_sep/GH42_3.2.1.23/GH42_3.2.1.23.spe.sum.csv")

# Summarize species to get top 10
spe.GH42_3.2.1.23.sum.sum <- spe.GH42_3.2.1.23.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```


### GH4_3.2.1.22 #################
```{r}
########## Phylum ##########
phy.GH4_3.2.1.22.sum <- import.phylum.sum('kaiju/mucin_sep/GH4_3.2.1.22/phylum')
write.csv(phy.GH4_3.2.1.22.sum, file = "kaiju/mucin_sep/GH4_3.2.1.22/GH4_3.2.1.22.phy.sum.csv")

# Summarize phyla to get top 10
phy.muc.sum.sum <- phy.muc.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH4_3.2.1.22.sum <- import.class.sum('kaiju/mucin_sep/GH4_3.2.1.22/class')
write.csv(cla.GH4_3.2.1.22.sum, file = "kaiju/mucin_sep/GH4_3.2.1.22/GH4_3.2.1.22.cla.sum.csv")

# Summarize classes to get top 10
cla.muc.sum.sum <- cla.muc.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH4_3.2.1.22.sum <- import.order.sum('kaiju/mucin_sep/GH4_3.2.1.22/order')
write.csv(ord.GH4_3.2.1.22.sum, file = "kaiju/mucin_sep/GH4_3.2.1.22/GH4_3.2.1.22.ord.sum.csv")

# Summarize orders to get top 10
ord.muc.sum.sum <- ord.muc.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH4_3.2.1.22.sum <- import.family.sum('kaiju/mucin_sep/GH4_3.2.1.22/family')
write.csv(fam.GH4_3.2.1.22.sum, file = "kaiju/mucin_sep/GH4_3.2.1.22/GH4_3.2.1.22.fam.sum.csv")

# Summarize families to get top 10
fam.muc.sum.sum <- fam.muc.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH4_3.2.1.22.sum <- import.genus.sum('kaiju/mucin_sep/GH4_3.2.1.22/genus')
write.csv(gen.GH4_3.2.1.22.sum, file = "kaiju/mucin_sep/GH4_3.2.1.22/GH4_3.2.1.22.gen.sum.csv")

# Summarize genera to get top 10
gen.muc.sum.sum <- gen.muc.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH4_3.2.1.22.sum <- import.species.sum('kaiju/mucin_sep/GH4_3.2.1.22/species')
write.csv(spe.GH4_3.2.1.22.sum, file = "kaiju/mucin_sep/GH4_3.2.1.22/GH4_3.2.1.22.spe.sum.csv")

# Summarize species to get top 10
spe.muc.sum.sum <- spe.muc.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```


### GH67_3.2.1.139
```{r}
########## Phylum ##########
phy.GH67_3.2.1.139.sum <- import.phylum.sum('kaiju/mucin_sep/GH67_3.2.1.139/phylum')
#write.csv(phy.GH67_3.2.1.139.sum, file = "kaiju/mucin_sep/GH67_3.2.1.139/GH67_3.2.1.139.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH67_3.2.1.139.sum.sum <- phy.GH67_3.2.1.139.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH67_3.2.1.139.sum <- import.class.sum('kaiju/mucin_sep/GH67_3.2.1.139/class')
#write.csv(cla.GH67_3.2.1.139.sum, file = "kaiju/mucin_sep/GH67_3.2.1.139/GH67_3.2.1.139.cla.sum.csv")

# Summarize classes to get top 10
cla.GH67_3.2.1.139.sum.sum <- cla.GH67_3.2.1.139.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH67_3.2.1.139.sum <- import.order.sum('kaiju/mucin_sep/GH67_3.2.1.139/order')
#write.csv(ord.GH67_3.2.1.139.sum, file = "kaiju/mucin_sep/GH67_3.2.1.139/GH67_3.2.1.139.ord.sum.csv")

# Summarize orders to get top 10
ord.GH67_3.2.1.139.sum.sum <- ord.GH67_3.2.1.139.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH67_3.2.1.139.sum <- import.family.sum('kaiju/mucin_sep/GH67_3.2.1.139/family')
#write.csv(fam.GH67_3.2.1.139.sum, file = "kaiju/mucin_sep/GH67_3.2.1.139/GH67_3.2.1.139.fam.sum.csv")

# Summarize families to get top 10
fam.GH67_3.2.1.139.sum.sum <- fam.GH67_3.2.1.139.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH67_3.2.1.139.sum <- import.genus.sum('kaiju/mucin_sep/GH67_3.2.1.139/genus')
#write.csv(gen.GH67_3.2.1.139.sum, file = "kaiju/mucin_sep/GH67_3.2.1.139/GH67_3.2.1.139.gen.sum.csv")

# Summarize genera to get top 10
gen.GH67_3.2.1.139.sum.sum <- gen.GH67_3.2.1.139.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH67_3.2.1.139.sum <- import.species.sum('kaiju/mucin_sep/GH67_3.2.1.139/species')
#write.csv(spe.GH67_3.2.1.139.sum, file = "kaiju/mucin_sep/GH67_3.2.1.139/GH67_3.2.1.139.spe.sum.csv")

# Summarize species to get top 10
spe.GH67_3.2.1.139.sum.sum <- spe.GH67_3.2.1.139.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```


### GH84_3.2.1.169
```{r}
########## Phylum ##########
phy.GH84_3.2.1.169.sum <- import.phylum.sum('kaiju/mucin_sep/GH84_3.2.1.169/phylum')
#write.csv(phy.GH84_3.2.1.169.sum, file = "kaiju/mucin_sep/GH84_3.2.1.169/GH84_3.2.1.169.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH84_3.2.1.169.sum.sum <- phy.GH84_3.2.1.169sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH84_3.2.1.169.sum <- import.class.sum('kaiju/mucin_sep/GH84_3.2.1.169/class')
#write.csv(cla.GH84_3.2.1.169.sum, file = "kaiju/mucin_sep/GH84_3.2.1.169/GH84_3.2.1.169.cla.sum.csv")

# Summarize classes to get top 10
cla.GH84_3.2.1.169.sum.sum <- cla.GH84_3.2.1.169sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH84_3.2.1.169.sum <- import.order.sum('kaiju/mucin_sep/GH84_3.2.1.169/order')
#write.csv(ord.GH84_3.2.1.169.sum, file = "kaiju/mucin_sep/GH84_3.2.1.169/GH84_3.2.1.169.ord.sum.csv")

# Summarize orders to get top 10
ord.GH84_3.2.1.169.sum.sum <- ord.GH84_3.2.1.169sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH84_3.2.1.169.sum <- import.family.sum('kaiju/mucin_sep/GH84_3.2.1.169/family')
#write.csv(fam.GH84_3.2.1.169.sum, file = "kaiju/mucin_sep/GH84_3.2.1.169/GH84_3.2.1.169.fam.sum.csv")

# Summarize families to get top 10
fam.GH84_3.2.1.169.sum.sum <- fam.GH84_3.2.1.169sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH84_3.2.1.169.sum <- import.genus.sum('kaiju/mucin_sep/GH84_3.2.1.169/genus')
#write.csv(gen.GH84_3.2.1.169.sum, file = "kaiju/mucin_sep/GH84_3.2.1.169/GH84_3.2.1.169.gen.sum.csv")

# Summarize genera to get top 10
gen.GH84_3.2.1.169.sum.sum <- gen.GH84_3.2.1.169sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH84_3.2.1.169.sum <- import.species.sum('kaiju/mucin_sep/GH84_3.2.1.169/species')
#write.csv(spe.GH84_3.2.1.169.sum, file = "kaiju/mucin_sep/GH84_3.2.1.169/GH84_3.2.1.169.spe.sum.csv")

# Summarize species to get top 10
spe.GH84_3.2.1.169.sum.sum <- spe.GH84_3.2.1.169sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```


### GH95_3.2.1.51
```{r}
########## Phylum ##########
phy.GH95_3.2.1.51.sum <- import.phylum.sum('kaiju/mucin_sep/GH95_3.2.1.51/phylum')
#write.csv(phy.GH95_3.2.1.51.sum, file = "kaiju/mucin_sep/GH95_3.2.1.51/GH95_3.2.1.51.phy.sum.csv")

# Summarize phyla to get top 10
phy.GH95_3.2.1.51.sum.sum <- phy.GH95_3.2.1.51.sum %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Mean))



########## Class ##########
cla.GH95_3.2.1.51.sum <- import.class.sum('kaiju/mucin_sep/GH95_3.2.1.51/class')
#write.csv(cla.GH95_3.2.1.51.sum, file = "kaiju/mucin_sep/GH95_3.2.1.51/GH95_3.2.1.51.cla.sum.csv")

# Summarize classes to get top 10
cla.GH95_3.2.1.51.sum.sum <- cla.GH95_3.2.1.51.sum %>%
  group_by(Class) %>%
  summarize(Mean = mean(Mean))



########## Order ##########
ord.GH95_3.2.1.51.sum <- import.order.sum('kaiju/mucin_sep/GH95_3.2.1.51/order')
#write.csv(ord.GH95_3.2.1.51.sum, file = "kaiju/mucin_sep/GH95_3.2.1.51/GH95_3.2.1.51.ord.sum.csv")

# Summarize orders to get top 10
ord.GH95_3.2.1.51.sum.sum <- ord.GH95_3.2.1.51.sum %>%
  group_by(Order) %>%
  summarize(Mean = mean(Mean))



########## Family ##########
fam.GH95_3.2.1.51.sum <- import.family.sum('kaiju/mucin_sep/GH95_3.2.1.51/family')
#write.csv(fam.GH95_3.2.1.51.sum, file = "kaiju/mucin_sep/GH95_3.2.1.51/GH95_3.2.1.51.fam.sum.csv")

# Summarize families to get top 10
fam.GH95_3.2.1.51.sum.sum <- fam.GH95_3.2.1.51.sum %>%
  group_by(Family) %>%
  summarize(Mean = mean(Mean))


########## Genus ##########
gen.GH95_3.2.1.51.sum <- import.genus.sum('kaiju/mucin_sep/GH95_3.2.1.51/genus')
#write.csv(gen.GH95_3.2.1.51.sum, file = "kaiju/mucin_sep/GH95_3.2.1.51/GH95_3.2.1.51.gen.sum.csv")

# Summarize genera to get top 10
gen.GH95_3.2.1.51.sum.sum <- gen.GH95_3.2.1.51.sum %>%
  group_by(Genus) %>%
  summarize(Mean = mean(Mean))


########## Species ##########
spe.GH95_3.2.1.51.sum <- import.species.sum('kaiju/mucin_sep/GH95_3.2.1.51/species')
#write.csv(spe.GH95_3.2.1.51.sum, file = "kaiju/mucin_sep/GH95_3.2.1.51/GH95_3.2.1.51.spe.sum.csv")

# Summarize species to get top 10
spe.GH95_3.2.1.51.sum.sum <- spe.GH95_3.2.1.51.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```

# Summarize species to get top 10
spe.muc.sum.sum <- spe.muc.sum %>%
  group_by(Species) %>%
  summarize(Mean = mean(Mean))
```