---
title: "KEGG Code"
author: "Edna Chiang"
date: "2/9/2021"
output: html_document
---

### Load Libraries
```{r}
library('readr')
library('pgirmess')
library('ggplot2')
library('grid')
library('phyloseq')
library('DESeq2')
library('phangorn')
library('vegan')
library('pheatmap')
library('RColorBrewer')
library('gplots')
library('tidyr')
library('dplyr')
library('stringr')
library('lme4')
library('picante')
library('ggdendro')
library('fitdistrplus')
library('amap')
library('labdsv')
theme_set(theme_bw())
set.seed(1)
```

### Load Functions
```{r}
source('scripts/misc.R')
source('scripts/simper.R')
source('scripts/pairwise.adonis.R')
```


### KEGG - Create phyloseq object
```{r}
# Load "otu" data
kegg1 <- read.csv('KEGG/musicc_outputs/test1/cat1.csv', header=T, row.names=1)
colnames(kegg1) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg2 <- read.csv('KEGG/musicc_outputs/test1/cat2.csv', header=T, row.names=1)
colnames(kegg2) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg2 <- kegg2[,-ncol(kegg2)]
kegg3 <- read.csv('KEGG/musicc_outputs/test1/path.csv', header=T, row.names=1)
colnames(kegg3) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg3 <- kegg3[,-ncol(kegg3)]
kegg3 <- kegg3[,-ncol(kegg3)]
#kegg4 <- read.csv('KEGG/musicc_outputs/test4/cat1.csv', header=T, row.names=1)
#colnames(kegg4) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")

# Load "tax" table
kegg.class <- read.csv('KEGG/KOID_Pathway_Classifications.csv', header = T)
unique.cat1 <- unique(kegg.class$Category1)
unique.cat1 <- data.frame(unique.cat1)
rownames(unique.cat1) <- unique.cat1[,1]
colnames(unique.cat1) <- "Category1"

cat2.merged <- paste(kegg.class$Category1, ":", kegg.class$Category2)
unique.cat2 <- unique(cat2.merged)
unique.cat2 <- data.frame(unique.cat2)
cat2.split <- strsplit(unique.cat2[,1], split = " : ")
cat2.df <- data.frame(matrix(nrow = length(cat2.split), ncol = 2))
for(i in 1:length(cat2.split)){
  cat2.df[i,] <- t(unlist(cat2.split[i]))
}
rownames(cat2.df) <- cat2.df[,2]
colnames(cat2.df) <- c("Category1", "Category2")

cat3.merged <- paste(kegg.class$Category1, ":", kegg.class$Category2, ":", kegg.class$Pathway)
unique.cat3 <- unique(cat3.merged)
unique.cat3 <- data.frame(unique.cat3)
cat3.split <- strsplit(unique.cat3[,1], split = " : ")
cat3.df <- data.frame(matrix(nrow = length(cat3.split), ncol = 3))
for(i in 1:length(cat3.split)){
  cat3.df[i,] <- t(unlist(cat3.split[i]))
}
rownames(cat3.df) <- cat3.df[,3]
colnames(cat3.df) <- c("Category1", "Category2", "Pathway")

# Prepare phyloseq object inputs
kegg1.otu <- otu_table(kegg1, taxa_are_rows = T)
cat1.tax <- tax_table(unique.cat1)
taxa_names(cat1.tax) <- unique.cat1[,1]
meta <- read.csv('metadata.csv', row.names=1)

kegg2.otu <- otu_table(kegg2, taxa_are_rows = T)
cat2.tax <- tax_table(cat2.df)
taxa_names(cat2.tax) <- cat2.df[,2]

kegg3.otu <- otu_table(kegg3, taxa_are_rows = T)
cat3.tax <- tax_table(cat3.df)
taxa_names(cat3.tax) <- cat3.df[,3]

# Create phyloseq object
kegg1.phy <- merge_phyloseq(kegg1.otu, cat1.tax, sample_data(meta))
kegg2.phy <- merge_phyloseq(kegg2.otu, cat2.tax, sample_data(meta))
kegg3.phy <- merge_phyloseq(kegg3.otu, cat3.tax, sample_data(meta))
```
### KEGG - Cat1 Kruskal-Wallis
```{r}
# Load data
kegg1 <- read.csv('KEGG/musicc_outputs/test1/cat1.csv', header=T, row.names=1)
kegg2 <- read.csv('KEGG/musicc_outputs/test2/cat1.csv', header=T, row.names=1)
kegg3 <- read.csv('KEGG/musicc_outputs/test3/cat1.csv', header=T, row.names=1)
#kegg4 <- read.csv('KEGG/musicc_outputs/test4/cat1.csv', header=T, row.names=1)



# Format data
kegg1.df <- data.frame(t(kegg1))
rownames(kegg1.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg1.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
kegg1.df$Season <- ordered(kegg1.df$Season, levels=c("Summer", "Winter", "Spring"))
kegg1.df$Diet <- c("Feed", "Feed", "Fast", "Fast", "Feed", "Feed", "Fast", "Feed", "Feed")
kegg1.df$Diet <- ordered(kegg1.df$Diet, levels=c("Feed", "Fast"))

kegg2.df <- data.frame(t(kegg2))
rownames(kegg2.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg2.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
kegg2.df$Season <- ordered(kegg2.df$Season, levels=c("Summer", "Winter", "Spring"))
kegg2.df$Diet <- c("Feed", "Feed", "Fast", "Fast", "Feed", "Feed", "Fast", "Feed", "Feed")
kegg2.df$Diet <- ordered(kegg1.df$Diet, levels=c("Feed", "Fast"))

kegg3.df <- data.frame(t(kegg3))
rownames(kegg3.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg3.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
kegg3.df$Season <- ordered(kegg3.df$Season, levels=c("Summer", "Winter", "Spring"))
kegg3.df$Diet <- c("Feed", "Feed", "Fast", "Fast", "Feed", "Feed", "Fast", "Feed", "Feed")
kegg3.df$Diet <- ordered(kegg1.df$Diet, levels=c("Feed", "Fast"))

#kegg4.df <- data.frame(t(kegg4))
#rownames(kegg4.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
#kegg4.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
#kegg4.df$Season <- ordered(kegg4.df$Season, levels=c("Summer", "Winter", "Spring"))


# Run Kruskal-Wallis on normalized KEGG counts
kegg1.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg1)))
colnames(kegg1.kw) <- rownames(kegg1)
for(i in 1:nrow(kegg1)){
  koid <- colnames(kegg1.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg1.df)
  kegg1.kw[,i] <- kw$p.value
}
kegg1.kw[2,] <- p.adjust(kegg1.kw[1,], method = "fdr")
which(kegg1.kw[2,] < 0.05)

kegg1.wil <- data.frame(matrix(nrow = 1, ncol = nrow(kegg1)))
colnames(kegg1.wil) <- rownames(kegg1)
for(i in 1:nrow(kegg1)){
  koid <- colnames(kegg1.df)[i]
  wil <- wilcox.test(formula = reformulate("Diet", koid), data = kegg1.df)
  kegg1.wil[,i] <- wil$p.value
}
kegg1.wil[2,] <- p.adjust(kegg1.wil[1,], method = "fdr")
which(kegg1.wil[2,] < 0.05)

kegg2.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg2)))
colnames(kegg2.kw) <- rownames(kegg2)
for(i in 1:nrow(kegg2)){
  koid <- colnames(kegg2.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg2.df)
  kegg2.kw[,i] <- kw$p.value
}
kegg2.kw[2,] <- p.adjust(kegg2.kw[1,], method = "fdr")
which(kegg2.kw[2,] < 0.05)

kegg2.wil <- data.frame(matrix(nrow = 1, ncol = nrow(kegg2)))
colnames(kegg2.wil) <- rownames(kegg2)
for(i in 1:nrow(kegg2)){
  koid <- colnames(kegg2.df)[i]
  wil <- wilcox.test(formula = reformulate("Diet", koid), data = kegg2.df)
  kegg2.wil[,i] <- wil$p.value
}
kegg2.wil[2,] <- p.adjust(kegg2.wil[1,], method = "fdr")
which(kegg2.wil[2,] < 0.05)


kegg3.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg3)))
colnames(kegg3.kw) <- rownames(kegg3)
for(i in 1:nrow(kegg3)){
  koid <- colnames(kegg3.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg3.df)
  kegg3.kw[,i] <- kw$p.value
}
kegg3.kw[2,] <- p.adjust(kegg3.kw[1,], method = "fdr")
which(kegg3.kw[2,] < 0.05)

kegg3.wil <- data.frame(matrix(nrow = 1, ncol = nrow(kegg3)))
colnames(kegg3.wil) <- rownames(kegg3)
for(i in 1:nrow(kegg3)){
  koid <- colnames(kegg3.df)[i]
  wil <- wilcox.test(formula = reformulate("Diet", koid), data = kegg3.df)
  kegg3.wil[,i] <- wil$p.value
}
kegg3.wil[2,] <- p.adjust(kegg3.wil[1,], method = "fdr")
which(kegg3.wil[2,] < 0.05)


#kegg4.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg4)))
#colnames(kegg4.kw) <- rownames(kegg4)
#for(i in 1:nrow(kegg4)){
#  koid <- colnames(kegg4.df)[i]
#  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg4.df)
#  kegg4.kw[,i] <- kw$p.value
#}
#kegg4.kw[2,] <- p.adjust(kegg4.kw[1,], method = "fdr")
#which(kegg4.kw[2,] < 0.05)
```


### KEGG - Cat2 Kruskal-Wallis
```{r}
# Load data
kegg1 <- read.csv('KEGG/musicc_outputs/test1/Cat2.csv', header=T, row.names=1)
kegg1 <- kegg1[,-ncol(kegg1)]
kegg2 <- read.csv('KEGG/musicc_outputs/test2/Cat2.csv', header=T, row.names=1)
kegg2 <- kegg2[,-ncol(kegg2)]
kegg3 <- read.csv('KEGG/musicc_outputs/test3/Cat2.csv', header=T, row.names=1)
kegg3 <- kegg3[,-ncol(kegg3)]
#kegg4 <- read.csv('KEGG/musicc_outputs/test4/Cat2.csv', header=T, row.names=1)
#kegg4 <- kegg4[,-ncol(kegg4)]


# Format data
kegg1.df <- data.frame(t(kegg1))
rownames(kegg1.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg1.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
kegg1.df$Season <- ordered(kegg1.df$Season, levels=c("Summer", "Winter", "Spring"))
kegg1.df$Diet <- c("Feed", "Feed", "Fast", "Fast", "Feed", "Feed", "Fast", "Feed", "Feed")
kegg1.df$Diet <- ordered(kegg1.df$Diet, levels=c("Feed", "Fast"))

kegg2.df <- data.frame(t(kegg2))
rownames(kegg2.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg2.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
kegg2.df$Season <- ordered(kegg2.df$Season, levels=c("Summer", "Winter", "Spring"))
kegg2.df$Diet <- c("Feed", "Feed", "Fast", "Fast", "Feed", "Feed", "Fast", "Feed", "Feed")
kegg2.df$Diet <- ordered(kegg2.df$Diet, levels=c("Feed", "Fast"))

kegg3.df <- data.frame(t(kegg3))
rownames(kegg3.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg3.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
kegg3.df$Season <- ordered(kegg3.df$Season, levels=c("Summer", "Winter", "Spring"))
kegg3.df$Diet <- c("Feed", "Feed", "Fast", "Fast", "Feed", "Feed", "Fast", "Feed", "Feed")
kegg3.df$Diet <- ordered(kegg3.df$Diet, levels=c("Feed", "Fast"))

#kegg4.df <- data.frame(t(kegg4))
#rownames(kegg4.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
#kegg4.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
#kegg4.df$Season <- ordered(kegg4.df$Season, levels=c("Summer", "Winter", "Spring"))


# Run Kruskal-Wallis on normalized KEGG counts
kegg1.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg1)))
colnames(kegg1.kw) <- rownames(kegg1)
for(i in 1:nrow(kegg1)){
  koid <- colnames(kegg1.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg1.df)
  kegg1.kw[,i] <- kw$p.value
}
kegg1.kw[2,] <- p.adjust(kegg1.kw[1,], method = "fdr")
which(kegg1.kw[2,] < 0.05)

kegg1.wil <- data.frame(matrix(nrow = 1, ncol = nrow(kegg1)))
colnames(kegg1.wil) <- rownames(kegg1)
for(i in 1:nrow(kegg1)){
  koid <- colnames(kegg1.df)[i]
  wil <- wilcox.test(formula = reformulate("Diet", koid), data = kegg1.df)
  kegg1.wil[,i] <- wil$p.value
}
kegg1.wil[2,] <- p.adjust(kegg1.wil[1,], method = "fdr")
which(kegg1.wil[2,] < 0.05)

kegg2.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg2)))
colnames(kegg2.kw) <- rownames(kegg2)
for(i in 1:nrow(kegg2)){
  koid <- colnames(kegg2.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg2.df)
  kegg2.kw[,i] <- kw$p.value
}
kegg2.kw[2,] <- p.adjust(kegg2.kw[1,], method = "fdr")
which(kegg2.kw[2,] < 0.05)

kegg2.wil <- data.frame(matrix(nrow = 1, ncol = nrow(kegg2)))
colnames(kegg2.wil) <- rownames(kegg2)
for(i in 1:nrow(kegg2)){
  koid <- colnames(kegg2.df)[i]
  wil <- wilcox.test(formula = reformulate("Diet", koid), data = kegg2.df)
  kegg2.wil[,i] <- wil$p.value
}
kegg2.wil[2,] <- p.adjust(kegg2.wil[1,], method = "fdr")
which(kegg2.wil[2,] < 0.05)

kegg3.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg3)))
colnames(kegg3.kw) <- rownames(kegg3)
for(i in 1:nrow(kegg3)){
  koid <- colnames(kegg3.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg3.df)
  kegg3.kw[,i] <- kw$p.value
}
kegg3.kw[2,] <- p.adjust(kegg3.kw[1,], method = "fdr")
which(kegg3.kw[2,] < 0.05)

kegg3.wil <- data.frame(matrix(nrow = 1, ncol = nrow(kegg3)))
colnames(kegg3.wil) <- rownames(kegg3)
for(i in 1:nrow(kegg3)){
  koid <- colnames(kegg3.df)[i]
  wil <- wilcox.test(formula = reformulate("Diet", koid), data = kegg3.df)
  kegg3.wil[,i] <- wil$p.value
}
kegg3.wil[2,] <- p.adjust(kegg3.wil[1,], method = "fdr")
which(kegg3.wil[2,] < 0.05)

#kegg4.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg4)))
#colnames(kegg4.kw) <- rownames(kegg4)
#for(i in 1:nrow(kegg4)){
#  koid <- colnames(kegg4.df)[i]
#  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg4.df)
#  kegg4.kw[,i] <- kw$p.value
#}
#kegg4.kw[2,] <- p.adjust(kegg4.kw[1,], method = "fdr")
#which(kegg4.kw[2,] < 0.05)
```


### KEGG - Path Kruskal-Wallis
```{r}
# Load data
kegg1 <- read.csv('KEGG/musicc_outputs/test1/path.csv', header=T, row.names=1)
kegg1 <- kegg1[,-ncol(kegg1)]
kegg1 <- kegg1[,-ncol(kegg1)]
kegg2 <- read.csv('KEGG/musicc_outputs/test2/path.csv', header=T, row.names=1)
kegg2 <- kegg2[,-ncol(kegg2)]
kegg2 <- kegg2[,-ncol(kegg2)]
kegg3 <- read.csv('KEGG/musicc_outputs/test3/path.csv', header=T, row.names=1)
kegg3 <- kegg3[,-ncol(kegg3)]
kegg3 <- kegg3[,-ncol(kegg3)]
#kegg4 <- read.csv('KEGG/musicc_outputs/test4/path.csv', header=T, row.names=1)
#kegg4 <- kegg4[,-ncol(kegg4)]
#kegg4 <- kegg4[,-ncol(kegg4)]


# Format data
kegg1.df <- data.frame(t(kegg1))
rownames(kegg1.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg1.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
kegg1.df$Season <- ordered(kegg1.df$Season, levels=c("Summer", "Winter", "Spring"))
kegg1.df$Diet <- c("Feed", "Feed", "Fast", "Fast", "Feed", "Feed", "Fast", "Feed", "Feed")
kegg1.df$Diet <- ordered(kegg1.df$Diet, levels=c("Feed", "Fast"))

kegg2.df <- data.frame(t(kegg2))
rownames(kegg2.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg2.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
kegg2.df$Season <- ordered(kegg2.df$Season, levels=c("Summer", "Winter", "Spring"))
kegg2.df$Diet <- c("Feed", "Feed", "Fast", "Fast", "Feed", "Feed", "Fast", "Feed", "Feed")
kegg2.df$Diet <- ordered(kegg2.df$Diet, levels=c("Feed", "Fast"))

kegg2.wil <- data.frame(matrix(nrow = 1, ncol = nrow(kegg2)))
colnames(kegg2.wil) <- rownames(kegg2)
for(i in 1:nrow(kegg2)){
  koid <- colnames(kegg2.df)[i]
  wil <- wilcox.test(formula = reformulate("Diet", koid), data = kegg2.df)
  kegg2.wil[,i] <- wil$p.value
}
kegg2.wil[2,] <- p.adjust(kegg2.wil[1,], method = "fdr")
which(kegg2.wil[2,] < 0.05)

kegg3.df <- data.frame(t(kegg3))
rownames(kegg3.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg3.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
kegg3.df$Season <- ordered(kegg3.df$Season, levels=c("Summer", "Winter", "Spring"))
kegg3.df$Diet <- c("Feed", "Feed", "Fast", "Fast", "Feed", "Feed", "Fast", "Feed", "Feed")
kegg3.df$Diet <- ordered(kegg3.df$Diet, levels=c("Feed", "Fast"))

#kegg4.df <- data.frame(t(kegg4))
#rownames(kegg4.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
#kegg4.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
#kegg4.df$Season <- ordered(kegg4.df$Season, levels=c("Summer", "Winter", "Spring"))


# Run Kruskal-Wallis on normalized KEGG counts
kegg1.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg1)))
colnames(kegg1.kw) <- rownames(kegg1)
for(i in 1:nrow(kegg1)){
  koid <- colnames(kegg1.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg1.df)
  kegg1.kw[,i] <- kw$p.value
}
kegg1.kw[2,] <- p.adjust(kegg1.kw[1,], method = "fdr")
which(kegg1.kw[2,] < 0.05)

kegg1.wil <- data.frame(matrix(nrow = 1, ncol = nrow(kegg1)))
colnames(kegg1.wil) <- rownames(kegg1)
for(i in 1:nrow(kegg1)){
  koid <- colnames(kegg1.df)[i]
  wil <- wilcox.test(formula = reformulate("Diet", koid), data = kegg1.df)
  kegg1.wil[,i] <- wil$p.value
}
kegg1.wil[2,] <- p.adjust(kegg1.wil[1,], method = "fdr")
which(kegg1.wil[2,] < 0.05)


kegg2.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg2)))
colnames(kegg2.kw) <- rownames(kegg2)
for(i in 1:nrow(kegg2)){
  koid <- colnames(kegg2.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg2.df)
  kegg2.kw[,i] <- kw$p.value
}
kegg2.kw[2,] <- p.adjust(kegg2.kw[1,], method = "fdr")
which(kegg2.kw[2,] < 0.05)

kegg3.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg3)))
colnames(kegg3.kw) <- rownames(kegg3)
for(i in 1:nrow(kegg3)){
  koid <- colnames(kegg3.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg3.df)
  kegg3.kw[,i] <- kw$p.value
}
kegg3.kw[2,] <- p.adjust(kegg3.kw[1,], method = "fdr")
which(kegg3.kw[2,] < 0.05)

kegg3.wil <- data.frame(matrix(nrow = 1, ncol = nrow(kegg3)))
colnames(kegg3.wil) <- rownames(kegg3)
for(i in 1:nrow(kegg3)){
  koid <- colnames(kegg3.df)[i]
  wil <- wilcox.test(formula = reformulate("Diet", koid), data = kegg3.df)
  kegg3.wil[,i] <- wil$p.value
}
kegg3.wil[2,] <- p.adjust(kegg3.wil[1,], method = "fdr")
which(kegg3.wil[2,] < 0.05)

#kegg4.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg4)))
#colnames(kegg4.kw) <- rownames(kegg4)
#for(i in 1:nrow(kegg4)){
#  koid <- colnames(kegg4.df)[i]
#  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg4.df)
#  kegg4.kw[,i] <- kw$p.value
#}
#kegg4.kw[2,] <- p.adjust(kegg4.kw[1,], method = "fdr")
#which(kegg4.kw[2,] < 0.05)
```



### KEGG - KOID Kruskal-Wallis
```{r}
# Load data
kegg1 <- read.csv('KEGG/musicc_outputs/KEGG_MUSiCC_all1.tab', header=T, sep = "\t", row.names = 1)
kegg2 <- read.csv('KEGG/musicc_outputs/KEGG_MUSiCC_all2.tab', header=T, sep = "\t", row.names = 1)
kegg3 <- read.csv('KEGG/musicc_outputs/KEGG_MUSiCC_all3.tab', header=T, sep = "\t", row.names = 1)
#kegg4 <- read.csv('KEGG/musicc_outputs/KEGG_MUSiCC_all4.tab', header=T, sep = "\t", row.names = 1)

# Format data
kegg1.df <- data.frame(t(kegg1))
rownames(kegg1.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg1.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
kegg1.df$Season <- ordered(kegg1.df$Season, levels=c("Summer", "Winter", "Spring"))
kegg1.df$Diet <- c("Feed", "Feed", "Fast", "Fast", "Feed", "Feed", "Fast", "Feed", "Feed")
kegg1.df$Diet <- ordered(kegg1.df$Diet, levels=c("Feed", "Fast"))

kegg2.df <- data.frame(t(kegg2))
rownames(kegg2.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg2.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
kegg2.df$Season <- ordered(kegg2.df$Season, levels=c("Summer", "Winter", "Spring"))
kegg2.df$Diet <- c("Feed", "Feed", "Fast", "Fast", "Feed", "Feed", "Fast", "Feed", "Feed")
kegg2.df$Diet <- ordered(kegg2.df$Diet, levels=c("Feed", "Fast"))

kegg3.df <- data.frame(t(kegg3))
rownames(kegg3.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
kegg3.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
kegg3.df$Season <- ordered(kegg3.df$Season, levels=c("Summer", "Winter", "Spring"))
kegg3.df$Diet <- c("Feed", "Feed", "Fast", "Fast", "Feed", "Feed", "Fast", "Feed", "Feed")
kegg3.df$Diet <- ordered(kegg3.df$Diet, levels=c("Feed", "Fast"))

#kegg4.df <- data.frame(t(kegg4))
#colnames(kegg4.df) <- kegg4.df[1,]
#kegg4.df <- kegg4.df[-1,]
#rownames(kegg4.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
#kegg4.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
#kegg4.df$Season <- ordered(kegg4.df$Season, levels=c("Summer", "Winter", "Spring"))


# Run Kruskal-Wallis on normalized KEGG counts
kegg1.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg1)))
colnames(kegg1.kw) <- kegg1[,1]
for(i in 1:nrow(kegg1)){
  koid <- colnames(kegg1.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg1.df)
  kegg1.kw[,i] <- kw$p.value
}
kegg1.kw[2,] <- p.adjust(kegg1.kw[1,], method = "fdr")
which(kegg1.kw[2,] < 0.05)

kegg1.wil <- data.frame(matrix(nrow = 1, ncol = nrow(kegg1)))
colnames(kegg1.wil) <- rownames(kegg1)
for(i in 1:nrow(kegg1)){
  koid <- colnames(kegg1.df)[i]
  wil <- wilcox.test(formula = reformulate("Diet", koid), data = kegg1.df)
  kegg1.wil[,i] <- wil$p.value
}
kegg1.wil[2,] <- p.adjust(kegg1.wil[1,], method = "fdr")
which(kegg1.wil[2,] < 0.05)

kegg2.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg2)))
colnames(kegg2.kw) <- kegg2[,1]
for(i in 1:nrow(kegg2)){
  koid <- colnames(kegg2.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg2.df)
  kegg2.kw[,i] <- kw$p.value
}
kegg2.kw[2,] <- p.adjust(kegg2.kw[1,], method = "fdr")
which(kegg2.kw[2,] < 0.05)

kegg2.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg2)))
colnames(kegg2.kw) <- rownames(kegg2)
for(i in 1:nrow(kegg2)){
  koid <- colnames(kegg2.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg2.df)
  kegg2.kw[,i] <- kw$p.value
}
kegg2.kw[2,] <- p.adjust(kegg2.kw[1,], method = "fdr")
which(kegg2.kw[2,] < 0.05)

kegg3.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg3)))
colnames(kegg3.kw) <- kegg3[,1]
for(i in 1:nrow(kegg3)){
  koid <- colnames(kegg3.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg3.df)
  kegg3.kw[,i] <- kw$p.value
}
kegg3.kw[2,] <- p.adjust(kegg3.kw[1,], method = "fdr")
which(kegg3.kw[2,] < 0.05)

kegg3.wil <- data.frame(matrix(nrow = 1, ncol = nrow(kegg3)))
colnames(kegg3.wil) <- rownames(kegg3)
for(i in 1:nrow(kegg3)){
  koid <- colnames(kegg3.df)[i]
  wil <- wilcox.test(formula = reformulate("Diet", koid), data = kegg3.df)
  kegg3.wil[,i] <- wil$p.value
}
kegg3.wil[2,] <- p.adjust(kegg3.wil[1,], method = "fdr")
which(kegg3.wil[2,] < 0.05)

#kegg4.kw <- data.frame(matrix(nrow = 1, ncol = nrow(kegg4)))
#colnames(kegg4.kw) <- kegg4[,1]
#for(i in 1:nrow(kegg4)){
#  koid <- colnames(kegg4.df)[i]
#  kw <- kruskal.test(formula = reformulate("Season", koid), data = kegg4.df)
#  kegg4.kw[,i] <- kw$p.value
#}
#kegg4.kw[2,] <- p.adjust(kegg4.kw[1,], method = "fdr")
#which(kegg4.kw[2,] < 0.05)
```


### KEGG - Cat1 Cluster Analysis
```{r}
kegg1 <- read.csv('KEGG/musicc_outputs/test1/cat1.csv', header=T, row.names=1)

kegg1.cat1.hell <- hellinger(kegg1)
kegg1.cat1.dist <- dist(t(kegg1.cat1.hell), method = "euclidean")
kegg1.cat1.dist.matrix <- as.matrix(kegg1.cat1.dist)
rownames(kegg1.cat1.dist.matrix) <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
colnames(kegg1.cat1.dist.matrix) <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")


# Dendrogram
kegg1.cat1.hclust <- hclust(kegg1.cat1.dist, method = "average")
kegg1.cat1.den <- as.dendrogram(kegg1.cat1.hclust)
kegg1.cat1.den.data <- dendro_data(kegg1.cat1.den, type = "rectangle")
kegg1.cat1.den.data$labels[,3] <- c("Summer", "Winter", "Winter", "Winter", "Summer", "Spring", "Spring", "Spring", "Summer")
kegg1.cat1.den.data$labels[,3] <- ordered(kegg1.cat1.den.data$labels[,3], levels=c("Summer", "Winter", "Spring"))


#tiff("dbcan.dendro.tiff", width=10, height=5, units="in", res=300)
ggplot(kegg1.cat1.den.data$segments) +
  geom_segment(aes(x=x, y=y, xend=xend, yend=yend)) +
  geom_text(data = kegg1.cat1.den.data$labels, 
            aes(x, y, label=label, colour=label, fontface = "bold"),
            hjust=0, size=5) +
  ylab("Hellinger Distance") +
  xlab("Season") +
  labs(colour = "Season") +
  coord_flip() +
  scale_y_reverse() +
  scale_color_manual(values=c("darkgoldenrod3", "dodgerblue3", "green4")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size=20),
        panel.border = element_blank(),
        axis.line.x = element_line(),
        legend.title = element_text(face="bold"),
        axis.title.x = element_text(face="bold", size=20),
        axis.title.y = element_text(face="bold", size=20))
#dev.off()





### PCoA
cat1.pcoa <- pcoa(kegg1.cat1.dist)
rownames(cat1.pcoa$vectors) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
cat1.phy.ord <- kegg1.phy
sample_data(cat1.phy.ord)$Season <- ordered(sample_data(cat1.phy.ord)$Season, levels = c("Summer", "Winter", "Spring"))


plot_ordination(physeq = cat1.phy.ord, ordination = cat1.pcoa, axes = c(1,2),
                color = "Season") +
  geom_point(size=5) +
  scale_color_manual(values=c("darkgoldenrod2", "dodgerblue3", "green3")) +
  ggtitle("Hellinger Distance") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(size=20),
        axis.title.y = element_text(size=20),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        plot.title = element_text(hjust=0.5, size=20))
  
 


### Test normality
hist(kegg1.cat1.dist)
qqnorm(kegg1.cat1.dist)
qqline(kegg1.cat1.dist)
shapiro.test(kegg1.cat1.dist)
  # p-value = 0.0794
  # Normal

### Run PERMANOVA on Hellinger distance
adonis(kegg1.cat1.dist ~ Season, data=meta, permutations = 99999)
  # p-value = 0.03138
beta.tax = betadisper(d=kegg1.cat1.dist, group=meta$Season)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.537




### Pairwise PERMANOVA comparisons
kegg1.cat1.dist.matrix <- as.matrix(kegg1.cat1.dist)
kegg1.cat1.dist.df <- data.frame(kegg1.cat1.dist.matrix)


# Summer vs. Winter
kegg1.cat1.sw.dist.df <- kegg1.cat1.dist.df[,-5]
kegg1.cat1.sw.dist.df <- kegg1.cat1.sw.dist.df[,-7:-8]
kegg1.cat1.sw.dist.df <- kegg1.cat1.sw.dist.df[-5,]
kegg1.cat1.sw.dist.df <- kegg1.cat1.sw.dist.df[-7:-8,]
kegg1.cat1.sw.dist <- as.dist(kegg1.cat1.sw.dist.df)
meta.sw <- meta[-which(meta$Season == "Spring"),]
adonis(kegg1.cat1.sw.dist ~ Season, data=meta.sw, permutations= 99999)
  # p-value = 0.2

# Summer vs. Spring
kegg1.cat1.sp.dist.df <- kegg1.cat1.dist.df[,-3:-4]
kegg1.cat1.sp.dist.df <- kegg1.cat1.sp.dist.df[,-5]
kegg1.cat1.sp.dist.df <- kegg1.cat1.sp.dist.df[-3:-4,]
kegg1.cat1.sp.dist.df <- kegg1.cat1.sp.dist.df[-5,]
kegg1.cat1.sp.dist <- as.dist(kegg1.cat1.sp.dist.df)
meta.sp <- meta[-which(meta$Season == "Winter"),]
adonis(kegg1.cat1.sp.dist ~ Season, data=meta.sp, permutations= 99999)
  # p-value = 0.2

# Spring vs. Winter
kegg1.cat1.wp.dist.df <- kegg1.cat1.dist.df[,-3:-4]
kegg1.cat1.wp.dist.df <- kegg1.cat1.wp.dist.df[,-5]
kegg1.cat1.wp.dist.df <- kegg1.cat1.wp.dist.df[-3:-4,]
kegg1.cat1.wp.dist.df <- kegg1.cat1.wp.dist.df[-5,]
kegg1.cat1.wp.dist <- as.dist(kegg1.cat1.wp.dist.df)
meta.wp <- meta[-which(meta$Season == "Summer"),]
adonis(kegg1.cat1.wp.dist ~ Season, data=meta.wp, permutations= 99999)
  # p-value = 0.2
```

### KEGG - Cat2 Cluster Analysis
```{r}
kegg1 <- read.csv('KEGG/musicc_outputs/test1/cat2.csv', header=T, row.names=1)
kegg1 <- kegg1[,-ncol(kegg1)]

kegg1.cat2.hell <- hellinger(kegg1)
kegg1.cat2.dist <- dist(t(kegg1.cat1.hell), method = "euclidean")
kegg1.cat2.dist.matrix <- as.matrix(kegg1.cat2.dist)
rownames(kegg1.cat2.dist.matrix) <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
colnames(kegg1.cat2.dist.matrix) <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")



# Dendrogram
kegg1.cat2.hclust <- hclust(kegg1.cat2.dist, method = "average")
kegg1.cat2.den <- as.dendrogram(kegg1.cat2.hclust)
kegg1.cat2.den.data <- dendro_data(kegg1.cat2.den, type = "rectangle")
kegg1.cat2.den.data$labels[,3] <- c("Summer", "Winter", "Winter", "Winter", "Summer", "Spring", "Spring", "Spring", "Summer")
kegg1.cat2.den.data$labels[,3] <- ordered(kegg1.cat2.den.data$labels[,3], levels=c("Summer", "Winter", "Spring"))


#tiff("dbcan.dendro.tiff", width=10, height=5, units="in", res=300)
plot_ordination(physeq = cat2.phy.ord, ordination = cat2.pcoa, axes = c(1,2),
                color = "Season") +
  geom_segment(aes(x=x, y=y, xend=xend, yend=yend)) +
  geom_text(data = kegg1.cat2.den.data$labels, 
            aes(x, y, label=label, colour=label, fontface = "bold"),
            hjust=0, size=5) +
  ylab("Hellinger Distance") +
  xlab("Season") +
  labs(colour = "Season") +
  coord_flip() +
  scale_y_reverse() +
  scale_color_manual(values=c("darkgoldenrod3", "dodgerblue3", "green4")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size=20),
        panel.border = element_blank(),
        axis.line.x = element_line(),
        legend.title = element_text(face="bold"),
        axis.title.x = element_text(face="bold", size=20),
        axis.title.y = element_text(face="bold", size=20))
#dev.off()





### PCoA
cat2.pcoa <- pcoa(kegg1.cat2.dist)
rownames(cat2.pcoa$vectors) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
cat2.phy.ord <- kegg1.phy
sample_data(cat2.phy.ord)$Season <- ordered(sample_data(cat2.phy.ord)$Season, levels = c("Summer", "Winter", "Spring"))


plot_ordination(physeq = cat2.phy.ord, ordination = cat2.pcoa, axes = c(1, 2),
                color="Season") + 
  geom_point(size=5) +
  scale_color_manual(values=c("darkgoldenrod2", "dodgerblue3", "green3")) +
  ggtitle("Hellinger Distance") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(size=20),
        axis.title.y = element_text(size=20),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        plot.title = element_text(hjust=0.5, size=20))
  
 


### Test normality
hist(kegg1.cat2.dist)
qqnorm(kegg1.cat2.dist)
qqline(kegg1.cat2.dist)
shapiro.test(kegg1.cat2.dist)
  # p-value = 0.0794
  # Not Normal

### Run PERMANOVA on Hellinger distance
adonis(kegg1.cat2.dist ~ Season, data=meta, permutations = 99999)
  # p-value = 0.03081
beta.tax = betadisper(d=kegg1.cat2.dist, group=meta$Season)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.509



### Pairwise PERMANOVA comparisons
kegg1.cat2.dist.matrix <- as.matrix(kegg1.cat2.dist)
kegg1.cat2.dist.df <- data.frame(kegg1.cat2.dist.matrix)


# Summer vs. Winter
kegg1.cat2.sw.dist.df <- kegg1.cat2.dist.df[,-5]
kegg1.cat2.sw.dist.df <- kegg1.cat2.sw.dist.df[,-7:-8]
kegg1.cat2.sw.dist.df <- kegg1.cat2.sw.dist.df[-5,]
kegg1.cat2.sw.dist.df <- kegg1.cat2.sw.dist.df[-7:-8,]
kegg1.cat2.sw.dist <- as.dist(kegg1.cat2.sw.dist.df)
meta.sw <- meta[-which(meta$Season == "Spring"),]
adonis(kegg1.cat2.sw.dist ~ Season, data=meta.sw, permutations= 99999)
  # p-value = 0.2

# Summer vs. Spring
kegg1.cat2.sp.dist.df <- kegg1.cat2.dist.df[,-3:-4]
kegg1.cat2.sp.dist.df <- kegg1.cat2.sp.dist.df[,-5]
kegg1.cat2.sp.dist.df <- kegg1.cat2.sp.dist.df[-3:-4,]
kegg1.cat2.sp.dist.df <- kegg1.cat2.sp.dist.df[-5,]
kegg1.cat2.sp.dist <- as.dist(kegg1.cat2.sp.dist.df)
meta.sp <- meta[-which(meta$Season == "Winter"),]
adonis(kegg1.cat2.sp.dist ~ Season, data=meta.sp, permutations= 99999)
  # p-value = 0.2

# Spring vs. Winter
kegg1.cat2.wp.dist.df <- kegg1.cat2.dist.df[,-3:-4]
kegg1.cat2.wp.dist.df <- kegg1.cat2.wp.dist.df[,-5]
kegg1.cat2.wp.dist.df <- kegg1.cat2.wp.dist.df[-3:-4,]
kegg1.cat2.wp.dist.df <- kegg1.cat2.wp.dist.df[-5,]
kegg1.cat2.wp.dist <- as.dist(kegg1.cat2.wp.dist.df)
meta.wp <- meta[-which(meta$Season == "Summer"),]
adonis(kegg1.cat2.wp.dist ~ Season, data=meta.wp, permutations= 99999)
  # p-value = 0.2
```


### KEGG - Pathway Cluster Analysis
```{r}
kegg1 <- read.csv('KEGG/musicc_outputs/test1/path.csv', header=T, row.names=1)
kegg1 <- kegg1[,-ncol(kegg1)]
kegg1 <- kegg1[,-ncol(kegg1)]

kegg1.path.hell <- hellinger(kegg1)
kegg1.path.dist <- dist(t(kegg1.path.hell), method = "euclidean")
kegg1.path.dist.matrix <- as.matrix(kegg1.path.dist)
rownames(kegg1.path.dist.matrix) <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
colnames(kegg1.path.dist.matrix) <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")


# Dendrogram
kegg1.path.hclust <- hclust(kegg1.path.dist, method = "average")
kegg1.path.den <- as.dendrogram(kegg1.path.hclust)
kegg1.path.den.data <- dendro_data(kegg1.path.den, type = "rectangle")
kegg1.path.den.data$labels[,3] <- c("Summer", "Winter", "Winter", "Winter", "Summer", "Spring", "Spring", "Spring", "Summer")
kegg1.path.den.data$labels[,3] <- ordered(kegg1.path.den.data$labels[,3], levels=c("Summer", "Winter", "Spring"))


#tiff("dbcan.dendro.tiff", width=10, height=5, units="in", res=300)
ggplot(kegg1.path.den.data$segments) +
  geom_segment(aes(x=x, y=y, xend=xend, yend=yend)) +
  geom_text(data = kegg1.path.den.data$labels, 
            aes(x, y, label=label, colour=label, fontface = "bold"),
            hjust=0, size=5) +
  ylab("Hellinger Distance") +
  xlab("Season") +
  labs(colour = "Season") +
  coord_flip() +
  scale_y_reverse() +
  scale_color_manual(values=c("darkgoldenrod3", "dodgerblue3", "green4")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size=20),
        panel.border = element_blank(),
        axis.line.x = element_line(),
        legend.title = element_text(face="bold"),
        axis.title.x = element_text(face="bold", size=20),
        axis.title.y = element_text(face="bold", size=20))
#dev.off()





### PCoA
path.pcoa <- pcoa(kegg1.path.dist)
rownames(path.pcoa$vectors) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
path.phy.ord <- kegg1.phy
sample_data(path.phy.ord)$Season <- ordered(sample_data(path.phy.ord)$Season, levels = c("Summer", "Winter", "Spring"))

plot_ordination(physeq = path.phy.ord, ordination = path.pcoa, axes = c(1, 2),
                color="Season") + 
  geom_point(size=5) +
  scale_color_manual(values=c("darkgoldenrod2", "dodgerblue3", "green3")) +
  ggtitle("Hellinger Distance") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(size=20),
        axis.title.y = element_text(size=20),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        plot.title = element_text(hjust=0.5, size=20))
  
 


### Test normality
hist(kegg1.path.dist)
qqnorm(kegg1.path.dist)
qqline(kegg1.path.dist)
shapiro.test(kegg1.path.dist)
  # p-value = 0.01237
  # Not Normal

### Run PERMANOVA on Euclidean distance
adonis(kegg1.path.dist ~ Season, data=meta, permutations = 99999)
  # p-value = 0.2285
beta.tax = betadisper(d=kegg1.path.dist, group=meta$Season)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.789




```