---
title: "COG Code"
author: "Edna Chiang"
date: "2/9/2021"
output: html_document
---

### Load Libraries
```{r}
library('readr')
library('pgirmess')
library('ggplot2')
library('grid')
library('phyloseq')
library('DESeq2')
library('phangorn')
library('vegan')
library('pheatmap')
library('RColorBrewer')
library('gplots')
library('tidyr')
library('dplyr')
library('stringr')
library('lme4')
library('picante')
library('ggdendro')
library('fitdistrplus')
library('amap')
library('labdsv')
library('NBPSeq')
theme_set(theme_bw())
set.seed(1)
```

### Load Functions
```{r}
source('scripts/misc.R')
source('scripts/simper.R')
source('scripts/pairwise.adonis.R')
```



### COG - Normalize by Universal Single-Copy Genes (DON'T RUN!)
```{r}
# Import raw COG count table
cog.counts <- read.csv('cog/COG.table.tab', header = T, sep = "\t")
rownames(cog.counts) <- cog.counts$COG
cog.counts <- cog.counts[,-1]
colnames(cog.counts) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")

# Prepare universal single-copy COGs
cog.usg <- c("COG0012", "COG0016", "COG0048", "COG0049", "COG0052", "COG0080", "COG0081", "COG0085", "COG0087", "COG0088", "COG0090", "COG0091", "COG0092", "COG0093", "COG0094", "COG0096", "COG0097", "COG0098", "COG0099", "COG0100", "COG0102", "COG0103", "COG0124", "COG0184", "COG0185", "COG0186", "COG0197", "COG0200", "COG0201", "COG0256", "COG0495", "COG0522", "COG0525", "COG0533", "COG0541")
cog.usg.df <- data.frame(matrix(NA, nrow = length(cog.usg), ncol = 9))
rownames(cog.usg.df) <- cog.usg
colnames(cog.usg.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")

# Pull out universal single-copy COGs
for(i in 1:nrow(cog.counts)){
  match <- sum(which(cog.usg == rownames(cog.counts)[i]))
  
  if (match > 0){
    rowNum <- which(rownames(cog.usg.df) == rownames(cog.counts)[i])
    cog.usg.df[rowNum,] <- cog.counts[i,]
  }
}

# Average universal single-copy COGs
cog.usg.avg <- data.frame(matrix(nrow = 1, ncol = 9))
colnames(cog.usg.avg) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
for(i in 1:ncol(cog.usg.df)){
  usgNum <- nrow(cog.usg.df)
  sum <- sum(cog.usg.df[,i])
  avg <- sum/usgNum
  cog.usg.avg[,i] <- avg
}

# Normalize COG counts by dividing by avg universal single-copy COGs for each sample
cog.norm <- data.frame(matrix(nrow = nrow(cog.counts), ncol = ncol(cog.counts)))
rownames(cog.norm) <- rownames(cog.counts)
colnames(cog.norm) <- colnames(cog.counts)
for(i in 1:ncol(cog.counts)){
 cog.norm[,i] = cog.counts[,i] / cog.usg.avg[,i]
}

# Save normalized COG counts
#write.table(cog.norm, file = "cog/cog.normalized.tab", sep = "\t")

# Normalize COG category counts by dividing by avg universal single-copy COGs for each sample
cog.cat <- read.csv('cog/cog.category.csv', header = T)
rownames(cog.cat) <- cog.cat[,1]
cog.cat <- cog.cat[,-1]
colnames(cog.cat) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
cog.cat.norm <- data.frame(matrix(nrow = 25, ncol = 9))
rownames(cog.cat.norm) <- rownames(cog.cat)
colnames(cog.cat.norm) <- colnames(cog.cat)
for(i in 1:ncol(cog.cat)){
 cog.cat.norm[,i] = cog.cat[,i] / cog.usg.avg[,i]
}

# Save normalized COG category counts
#write.csv(cog.cat.norm, file = "cog/cog.category.normalized.csv")

```

### COG - Create phyloseq objects (DON'T RUN!)
```{r}
### Count-level ###

# Load data
cog.norm <- read.csv('cog/cog.normalized.tab', header = T, sep = "\t")

# Identify COGs that appear in only 1 sample
cog.rem <- list()
for(i in 1:nrow(cog.norm)){
  empty <- length(which(cog.norm[i,] == 0))
    # Identifies number of samples without COG
  if(empty > 7){
    # If COG appears in only 1 sample
    cog.rem <- append(cog.rem, i)
      # Create list of COGs that appear in only 1 sample
  }
}
cog.rem.row <- as.numeric(cog.rem)
  # Convert list to numeric

# Remove COGs that appear in only 1 sample
cog.norm.rem <- cog.norm[-cog.rem.row,]
colnames(cog.norm.rem) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")

# Format data
cog.df <- data.frame(t(cog.norm.rem))
rownames(cog.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
cog.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
cog.df$Season <- ordered(cog.df$Season, levels=c("Summer", "Winter", "Spring"))

# Load COG "tax_table"
cog.cat <- read.csv('cog/cog.classifications.tab', header = T, sep = "\t")
cog.tax <- data.frame(cog.cat[,-2:-3])

# Prepare phyloseq object inputs
cog.otu <- otu_table(cog.norm.rem, taxa_are_rows = T)
cog.tax <- tax_table(cog.tax)
taxa_names(cog.tax) <- cog.tax[,1]
meta <- read.csv('dbcan/dbcan.spades.metadata.csv', row.names=1)

# Create phyloseq object
cog.phy <- merge_phyloseq(cog.otu, cog.tax, sample_data(meta))
#save(cog.phy, file = "cog.phy.Rdata")



### Category-level ###

# Create phyloseq object
colnames(cog.cat) <- c("COG", "Category", "Annotation")
cog.cat.tax <- data.frame(cog.cat$Category)
cog.cat.tax[,2] <- cog.cat$COG
colnames(cog.cat.tax) <- c("Category", "COG")
cog.cat.tax <- tax_table(cog.cat.tax)
taxa_names(cog.cat.tax) <- cog.cat.tax[,2]
cog.cat.phy <- merge_phyloseq(cog.otu, cog.cat.tax, sample_data(meta))
colnames(tax_table(cog.cat.tax)) <- c("Category", "COG")

# Merge by category
cog.cat.phy <- tax_glom(cog.cat.phy, taxrank = "Category")

# Create updated COG category counts
cog.cat.otu <- data.frame(otu_table(cog.cat.phy))
cog.cat.tax <- data.frame(tax_table(cog.cat.phy))
cog.cat.norm <- data.frame(matrix(nrow = 25, ncol = 9))
rownames(cog.cat.norm) <- c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "Y", "Z")
colnames(cog.cat.norm) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
match <- which(grepl("A", cog.cat.tax[,1]))
cog.cat.norm[1,] <- cog.cat.otu[81,] + cog.cat.otu[106,] + cog.cat.otu[115,] + cog.cat.otu[118,]
match <- which(grepl("B", cog.cat.tax[,1]))
cog.cat.norm[2,] <- cog.cat.otu[3,] + cog.cat.otu[62,] + cog.cat.otu[80,] + cog.cat.otu[103,] + cog.cat.otu[109,] + cog.cat.otu[122,] + cog.cat.otu[129,]
match <- which(grepl("C", cog.cat.tax[,1]))
cog.cat.norm[3,] <- cog.cat.otu[20,] + cog.cat.otu[29,] + cog.cat.otu[33,] + cog.cat.otu[36,] + cog.cat.otu[40,] + cog.cat.otu[42,] + cog.cat.otu[52,] + cog.cat.otu[75,] + cog.cat.otu[97,] + cog.cat.otu[98,] + cog.cat.otu[102,] + cog.cat.otu[134,]
match <- which(grepl("D", cog.cat.tax[,1]))
cog.cat.norm[4,] <- cog.cat.otu[58,] + cog.cat.otu[73,] + cog.cat.otu[79,] + cog.cat.otu[103,] + cog.cat.otu[104,] + cog.cat.otu[105,] + cog.cat.otu[106,] + cog.cat.otu[107,] + cog.cat.otu[110,] + cog.cat.otu[112,] + cog.cat.otu[113,] + cog.cat.otu[114,] + cog.cat.otu[115,] + cog.cat.otu[117,] + cog.cat.otu[119,] + cog.cat.otu[120,] + cog.cat.otu[121,] + cog.cat.otu[122,] + cog.cat.otu[127,]
match <- which(grepl("E", cog.cat.tax[,1]))
cog.cat.norm[5,] <- cog.cat.otu[1,] + cog.cat.otu[2,] + cog.cat.otu[4,] + cog.cat.otu[7,] + cog.cat.otu[9,] + cog.cat.otu[13,] + cog.cat.otu[14,] + cog.cat.otu[17,] + cog.cat.otu[18,] + cog.cat.otu[20,] + cog.cat.otu[21,] + cog.cat.otu[24,] + cog.cat.otu[43,] + cog.cat.otu[48,] + cog.cat.otu[56,] + cog.cat.otu[86,] + cog.cat.otu[89,]
match <- which(grepl("F", cog.cat.tax[,1]))
cog.cat.norm[6,] <- cog.cat.otu[6,] + cog.cat.otu[12,] + cog.cat.otu[17,] + cog.cat.otu[18,] + cog.cat.otu[31,] + cog.cat.otu[35,] + cog.cat.otu[65,] + cog.cat.otu[77,]
match <- which(grepl("G", cog.cat.tax[,1]))
cog.cat.norm[7,] <- cog.cat.otu[4,] + cog.cat.otu[11,] + cog.cat.otu[15,] + cog.cat.otu[21,] + cog.cat.otu[31,] + cog.cat.otu[43,] + cog.cat.otu[74,] + cog.cat.otu[75,] + cog.cat.otu[76,] + cog.cat.otu[82,] + cog.cat.otu[86,] + cog.cat.otu[94,] + cog.cat.otu[95,] + cog.cat.otu[108,] + cog.cat.otu[128,]
match <- which(grepl("H", cog.cat.tax[,1]))
cog.cat.norm[8,] <- cog.cat.otu[1,] + cog.cat.otu[2,] + cog.cat.otu[5,] + cog.cat.otu[33,] + cog.cat.otu[38,] + cog.cat.otu[52,] + cog.cat.otu[53,] + cog.cat.otu[54,] + cog.cat.otu[55,] + cog.cat.otu[57,] + cog.cat.otu[77,] + cog.cat.otu[94,] + cog.cat.otu[98,]
match <- which(grepl("I", cog.cat.tax[,1]))
cog.cat.norm[9,] <- cog.cat.otu[8,] + cog.cat.otu[37,] + cog.cat.otu[47,] + cog.cat.otu[50,] + cog.cat.otu[51,] + cog.cat.otu[55,] + cog.cat.otu[71,] + cog.cat.otu[116,] + cog.cat.otu[134,]
match <- which(grepl("J", cog.cat.tax[,1]))
cog.cat.norm[10,] <- cog.cat.otu[5,] + cog.cat.otu[7,] + cog.cat.otu[22,] + cog.cat.otu[27,] + cog.cat.otu[35,] + cog.cat.otu[60,] + cog.cat.otu[79,] + cog.cat.otu[81,] + cog.cat.otu[125,] + cog.cat.otu[133,]
match <- which(grepl("K", cog.cat.tax[,1]))
cog.cat.norm[11,] <- cog.cat.otu[10,] + cog.cat.otu[16,] + cog.cat.otu[27,] + cog.cat.otu[28,] + cog.cat.otu[34,] + cog.cat.otu[45,] + cog.cat.otu[56,] + cog.cat.otu[59,] + cog.cat.otu[62,] + cog.cat.otu[70,] + cog.cat.otu[76,] + cog.cat.otu[87,] + cog.cat.otu[90,] + cog.cat.otu[91,] + cog.cat.otu[96,] + cog.cat.otu[104,] + cog.cat.otu[105,] + cog.cat.otu[109,] + cog.cat.otu[112,] + cog.cat.otu[115,] + cog.cat.otu[120,] + cog.cat.otu[127,] + cog.cat.otu[129,]
match <- which(grepl("L", cog.cat.tax[,1]))
cog.cat.norm[12,] <- cog.cat.otu[25,] + cog.cat.otu[27,] + cog.cat.otu[28,] + cog.cat.otu[34,] + cog.cat.otu[46,] + cog.cat.otu[59,] + cog.cat.otu[67,] + cog.cat.otu[101,] + cog.cat.otu[103,] + cog.cat.otu[106,] + cog.cat.otu[127,] + cog.cat.otu[129,]
match <- which(grepl("M", cog.cat.tax[,1]))
cog.cat.norm[13,] <- cog.cat.otu[9,] + cog.cat.otu[15,] + cog.cat.otu[19,] + cog.cat.otu[37,] + cog.cat.otu[47,] + cog.cat.otu[60,] + cog.cat.otu[69,] + cog.cat.otu[88,] + cog.cat.otu[95,] + cog.cat.otu[100,] + cog.cat.otu[131,]
match <- which(grepl("N", cog.cat.tax[,1]))
cog.cat.norm[14,] <- cog.cat.otu[49,] + cog.cat.otu[63,] + cog.cat.otu[68,] + cog.cat.otu[78,] + cog.cat.otu[84,] + cog.cat.otu[87,] + cog.cat.otu[92,] + cog.cat.otu[99,] + cog.cat.otu[130,] + cog.cat.otu[131,]
match <- which(grepl("O", cog.cat.tax[,1]))
cog.cat.norm[15,] <- cog.cat.otu[10,] + cog.cat.otu[29,] + cog.cat.otu[32,] + cog.cat.otu[44,] + cog.cat.otu[63,] + cog.cat.otu[66,] + cog.cat.otu[67,] + cog.cat.otu[68,] + cog.cat.otu[78,] + cog.cat.otu[96,] + cog.cat.otu[99,] + cog.cat.otu[102,] + cog.cat.otu[108,] + cog.cat.otu[117,] + cog.cat.otu[121,] + cog.cat.otu[123,] + cog.cat.otu[125,] + cog.cat.otu[128,] + cog.cat.otu[131,] + cog.cat.otu[133,]
match <- which(grepl("P", cog.cat.tax[,1]))
cog.cat.norm[16,] <- cog.cat.otu[6,] + cog.cat.otu[14,] + cog.cat.otu[21,] + cog.cat.otu[40,] + cog.cat.otu[54,] + cog.cat.otu[72,] + cog.cat.otu[83,] + cog.cat.otu[88,] + cog.cat.otu[92,] + cog.cat.otu[93,] + cog.cat.otu[132,]
match <- which(grepl("Q", cog.cat.tax[,1]))
cog.cat.norm[17,] <- cog.cat.otu[3,] + cog.cat.otu[8,] + cog.cat.otu[26,] + cog.cat.otu[51,] + cog.cat.otu[57,] + cog.cat.otu[61,] + cog.cat.otu[85,] + cog.cat.otu[89,] + cog.cat.otu[91,] + cog.cat.otu[97,] + cog.cat.otu[132,]
match <- which(grepl("R", cog.cat.tax[,1]))
cog.cat.norm[18,] <- cog.cat.otu[12,] + cog.cat.otu[16,] + cog.cat.otu[21,] + cog.cat.otu[23,] + cog.cat.otu[24,] + cog.cat.otu[25,] + cog.cat.otu[26,] + cog.cat.otu[28,] + cog.cat.otu[31,] + cog.cat.otu[36,] + cog.cat.otu[43,] + cog.cat.otu[51,] + cog.cat.otu[52,] + cog.cat.otu[53,] + cog.cat.otu[71,] + cog.cat.otu[82,] + cog.cat.otu[83,] + cog.cat.otu[94,] + cog.cat.otu[100,] + cog.cat.otu[113,] + cog.cat.otu[114,]
match <- which(grepl("S", cog.cat.tax[,1]))
cog.cat.norm[19,] <- cog.cat.otu[64,]
match <- which(grepl("T", cog.cat.tax[,1]))
cog.cat.norm[20,] <- cog.cat.otu[28,] + cog.cat.otu[39,] + cog.cat.otu[45,] + cog.cat.otu[48,] + cog.cat.otu[49,] + cog.cat.otu[66,] + cog.cat.otu[73,] + cog.cat.otu[74,] + cog.cat.otu[85,] + cog.cat.otu[90,] + cog.cat.otu[92,] + cog.cat.otu[93,] + cog.cat.otu[96,] + cog.cat.otu[99,] + cog.cat.otu[103,] + cog.cat.otu[104,] + cog.cat.otu[105,] + cog.cat.otu[107,] + cog.cat.otu[114,]
match <- which(grepl("U", cog.cat.tax[,1]))
cog.cat.norm[21,] <- cog.cat.otu[41,] + cog.cat.otu[44,] + cog.cat.otu[46,] + cog.cat.otu[68,] + cog.cat.otu[69,] + cog.cat.otu[78,] + cog.cat.otu[84,] + cog.cat.otu[87,] + cog.cat.otu[92,] + cog.cat.otu[103,] + cog.cat.otu[108,] + cog.cat.otu[110,] + cog.cat.otu[111,] + cog.cat.otu[116,] + cog.cat.otu[126,]
match <- which(grepl("V", cog.cat.tax[,1]))
cog.cat.norm[22,] <- cog.cat.otu[30,]
match <- which(grepl("W", cog.cat.tax[,1]))
cog.cat.norm[23,] <- cog.cat.otu[126,]
match <- which(grepl("Y", cog.cat.tax[,1]))
cog.cat.norm[24,] <- cog.cat.otu[111,]
match <- which(grepl("Z", cog.cat.tax[,1]))
cog.cat.norm[25,] <- cog.cat.otu[114,] + cog.cat.otu[119,] + cog.cat.otu[123,] + cog.cat.otu[124,]

# Created updated COG category physeq object
cog.cat.tax <- cog.cat.norm
cog.cat.tax.cat <- data.frame(rownames(cog.cat.norm))
cog.cat.tax.tax <- tax_table(cog.cat.tax.cat)
colnames(cog.cat.tax.tax) <- "Category"
rownames(cog.cat.tax.tax) <- cog.cat.tax.tax[,1]
cog.cat.phy <- merge_phyloseq(otu_table(cog.cat.norm, taxa_are_rows=T), cog.cat.tax.tax, sample_data(meta))
#save(cog.cat.phy, file = "cog.cat.phy.Rdata")
#write.csv(data.frame(otu_table(cog.cat.phy)), file = "cog/cog.category.normalized.csv")
```
### COG - Load physeq objects
```{r}
load("cog.phy.Rdata")
load("cog.cat.phy.Rdata")
meta <- read.csv('dbcan/dbcan.spades.metadata.csv', row.names=1)
```


### COG - General COG Stats
```{r}
# Load data
cog.stats <- read.csv('cog/cog.stats.csv', row.names = 1, header = T)
cog.stats <- as.matrix(cog.stats)

# Test normality - % COGs from ORFs
hist(cog.stats[3,])
qqnorm(cog.stats[3,])
qqline(cog.stats[3,])
shapiro.test(cog.stats[3,])
  # p-value = 0.108
  # Normal

# Test normality - Unique COGs
hist(cog.stats[4,])
qqnorm(cog.stats[4,])
qqline(cog.stats[4,])
shapiro.test(cog.stats[4,])
  # p-value = 0.1712
  # Normal

# Format for ANOVA
cog.stats <- data.frame(t(cog.stats))
rownames(cog.stats) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
cog.stats$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")

# Test w/ ANOVA
summary(aov(Prop_COGs ~ Season, data = cog.stats))
  # p-value = 0.634
summary(aov(Unique_COGs ~ Season, data = cog.stats))
  # p-value = 0.51

ggplot(cog.stats, aes(x=Season, y=Prop_COGs, fill=Season)) +
  geom_dotplot(binaxis='y', stackdir='center', dotsize=1, stackratio=1.15) +
  ylab("% ORFs annotated as COG (%)") +
  scale_fill_manual(values=c("darkgoldenrod2", "dodgerblue3", "green3")) +
  scale_y_continuous(breaks = c(37, 40, 43, 46, 49), limits=c(37, 49)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text = element_text(face="bold"),
        strip.text.x = element_text(size=11),
        legend.title = element_text(face="bold"))

ggplot(cog.stats, aes(x=Season, y=Unique_COGs, fill=Season)) +
  geom_dotplot(binaxis='y', stackdir='center', dotsize=1, stackratio=1.15) +
  ylab("Unique COGs") +
  scale_fill_manual(values=c("darkgoldenrod2", "dodgerblue3", "green3")) +
  scale_y_continuous(breaks = c(3200, 3400, 3600), limits=c(3200, 3600)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text = element_text(face="bold"),
        strip.text.x = element_text(size=11),
        legend.title = element_text(face="bold"))
```
### COG Category - Kruskal-Wallis
```{r}
# Load data
cog.cat <- data.frame(otu_table(cog.cat.phy))
colnames(cog.cat) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")

# Format data
cog.cat.df <- data.frame(t(cog.cat))
cog.cat.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
cog.cat.df$Season <- ordered(cog.cat.df$Season, levels=c("Summer", "Winter", "Spring"))
cog.cat.mat <- as.matrix(t(cog.cat.df))




# Run Kruskal-Wallis on all categories
cog.cat.kw <- data.frame(matrix(nrow = 1, ncol = nrow(cog.cat)))
colnames(cog.cat.kw) <- rownames(cog.cat)
for(i in 1:nrow(cog.cat)){
  cogName <- colnames(cog.cat.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", cogName), data = cog.cat.df)
  cog.cat.kw[,i] <- kw$p.value
}
cog.cat.kw[2,] <- p.adjust(cog.cat.kw[1,], method = "fdr")
which(cog.cat.kw[2,] < 0.05)
```


### COG - Kruskal-Wallis
```{r}
# Load data
cog.norm <- read.csv('cog/cog.normalized.tab', header = T, sep = "\t")

# Identify COGs that appear in only 1 sample
cog.rem <- list()
for(i in 1:nrow(cog.norm)){
  empty <- length(which(cog.norm[i,] == 0))
    # Identifies number of samples without COG
  if(empty > 7){
    # If COG appears in only 1 sample
    cog.rem <- append(cog.rem, i)
      # Create list of COGs that appear in only 1 sample
  }
}
cog.rem.row <- as.numeric(cog.rem)
  # Convert list to numeric

# Remove COGs that appear in only 1 sample
cog.norm.rem <- cog.norm[-cog.rem.row,]

# Format data
cog.df <- data.frame(t(cog.norm))
rownames(cog.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
cog.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
cog.df$Season <- ordered(cog.df$Season, levels=c("Summer", "Winter", "Spring"))
cog.mat <- as.matrix(t(cog.df))




# Run Kruskal-Wallis on all COGs
cog.kw <- data.frame(matrix(nrow = 1, ncol = nrow(cog.norm.rem)))
colnames(cog.kw) <- rownames(cog.norm.rem)
for(i in 1:nrow(cog.norm.rem)){
  cogName <- colnames(cog.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", cogName), data = cog.df)
  cog.kw[,i] <- kw$p.value
}
cog.kw[2,] <- p.adjust(cog.kw[1,], method = "fdr")
which(cog.kw[2,] < 0.05)

```


### COG - Clustering
```{r}
# https://sites.google.com/site/mb3gustame/reference/dissimilarity
cog <- data.frame(otu_table(cog.phy))
colnames(cog) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", 
                        "3773", "3775")
cog.hell <- hellinger(t(cog))
cog.dist <- dist(cog.hell, method = "euclidean")
cog.dist.matrix <- as.matrix(cog.dist)
rownames(cog.dist.matrix) <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
colnames(cog.dist.matrix) <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")

# Dendrogram
cog.hclust <- hclust(cog.dist, method = "average")
cog.den <- as.dendrogram(cog.hclust)
cog.den.data <- dendro_data(cog.den, type = "rectangle")
cog.den.data$labels[,3] <- c("Summer", "Winter", "Winter", "Winter", "Summer", "Spring", "Spring", "Spring", "Summer")
cog.den.data$labels[,3] <- ordered(cog.den.data$labels[,3], levels=c("Summer", "Winter", "Spring"))


#tiff("cog.dendro.tiff", width=10, height=5, units="in", res=300)
ggplot(cog.den.data$segments) +
  geom_segment(aes(x=x, y=y, xend=xend, yend=yend)) +
  geom_text(data = cog.den.data$labels, aes(x, y, label=label, colour=label, fontface = "bold"),
            hjust=0, size=5) +
  ylab("Hellinger Distance") +
  xlab("Season") +
  labs(colour = "Season") +
  coord_flip() +
  scale_y_reverse() +
  scale_color_manual(values=c("darkgoldenrod3", "dodgerblue3", "green4")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size=20),
        panel.border = element_blank(),
        axis.line.x = element_line(),
        legend.title = element_text(face="bold"),
        axis.title.x = element_text(face="bold", size=20),
        axis.title.y = element_text(face="bold", size=20))
#dev.off()







### PCoA
cog.pcoa <- pcoa(cog.dist)
  # Total variance explained = 62.4
cog.phy.ord <- cog.phy
sample_data(cog.phy.ord)$Season <- ordered(sample_data(cog.phy.ord)$Season, levels = c("Summer", "Winter", "Spring"))


#tiff("cog.pcoa.tiff", width=8, height=6, units="in", res=300)
plot_ordination(physeq = cog.phy.ord, ordination = cog.pcoa, axes = c(1,2),
                color = "Season") +
  geom_point(size=5) +
  scale_color_manual(values=c("darkgoldenrod2", "dodgerblue3", "green3")) +
  ggtitle("Hellinger Distance") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(size=20),
        axis.title.y = element_text(size=20),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        plot.title = element_text(hjust=0.5, size=20))
#dev.off()






### Test normality
hist(cog.dist)
qqnorm(cog.dist)
qqline(cog.dist)
shapiro.test(cog.dist)
  # p-value = 0.05018
  # Normal

### Run PERMANOVA on Hellinger distance
adonis(cog.dist ~ Season, data=meta, permutations = 99999)
  # p-value = 0.02111
beta.tax = betadisper(d=cog.dist, group=meta$Season)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.738




### Pairwise PERMANOVA comparisons
cog.dist.matrix <- as.matrix(cog.dist)
cog.dist.df <- data.frame(cog.dist.matrix)


# Summer vs. Winter
cog.sw.dist.df <- cog.dist.df[,-5]
cog.sw.dist.df <- cog.sw.dist.df[,-7:-8]
cog.sw.dist.df <- cog.sw.dist.df[-5,]
cog.sw.dist.df <- cog.sw.dist.df[-7:-8,]
cog.sw.dist <- as.dist(cog.sw.dist.df)
meta.sw <- meta[-which(meta$Season == "Spring"),]
adonis(cog.sw.dist ~ Season, data=meta.sw, permutations= 99999)
  # p-value = 0.2

# Summer vs. Spring
cog.sp.dist.df <- cog.dist.df[,-3:-4]
cog.sp.dist.df <- cog.sp.dist.df[,-5]
cog.sp.dist.df <- cog.sp.dist.df[-3:-4,]
cog.sp.dist.df <- cog.sp.dist.df[-5,]
cog.sp.dist <- as.dist(cog.sp.dist.df)
meta.sp <- meta[-which(meta$Season == "Winter"),]
adonis(cog.sp.dist ~ Season, data=meta.sp, permutations= 99999)
  # p-value = 0.2

# Spring vs. Winter
cog.wp.dist.df <- cog.dist.df[,-3:-4]
cog.wp.dist.df <- cog.wp.dist.df[,-5]
cog.wp.dist.df <- cog.wp.dist.df[-3:-4,]
cog.wp.dist.df <- cog.wp.dist.df[-5,]
cog.wp.dist <- as.dist(cog.wp.dist.df)
meta.wp <- meta[-which(meta$Season == "Summer"),]
adonis(cog.wp.dist ~ Season, data=meta.wp, permutations= 99999)
  # p-value = 0.2

```

### COG Category - Clustering
```{r}
# https://sites.google.com/site/mb3gustame/reference/dissimilarity
cog.cat <- data.frame(otu_table(cog.cat.phy))
colnames(cog.cat) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", 
                        "3773", "3775")
cog.cat.hell <- hellinger(t(cog.cat))
cog.cat.dist <- dist(cog.cat.hell, method = "euclidean")
cog.cat.dist.matrix <- as.matrix(cog.cat.dist)
rownames(cog.cat.dist.matrix) <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
colnames(cog.cat.dist.matrix) <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")



# Dendrogram
cog.cat.hclust <- hclust(cog.cat.dist, method = "average")
cog.cat.den <- as.dendrogram(cog.cat.hclust)
cog.cat.den.data <- dendro_data(cog.cat.den, type = "rectangle")
cog.cat.den.data$labels[,3] <- c("Summer", "Winter", "Winter", "Winter", "Summer", "Spring", "Spring", "Spring", "Summer")
cog.cat.den.data$labels[,3] <- ordered(cog.cat.den.data$labels[,3], levels=c("Summer", "Winter", "Spring"))


#tiff("cog.cat.dendro.tiff", width=10, height=5, units="in", res=300)
ggplot(cog.cat.den.data$segments) +
  geom_segment(aes(x=x, y=y, xend=xend, yend=yend)) +
  geom_text(data = cog.cat.den.data$labels, aes(x, y, label=label, colour=label, fontface = "bold"),
            hjust=0, size=5) +
  ylab("Hellinger Distance") +
  xlab("Season") +
  labs(colour = "Season") +
  coord_flip() +
  scale_y_reverse() +
  scale_color_manual(values=c("darkgoldenrod3", "dodgerblue3", "green4")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size=20),
        panel.border = element_blank(),
        axis.line.x = element_line(),
        legend.title = element_text(face="bold"),
        axis.title.x = element_text(face="bold", size=20),
        axis.title.y = element_text(face="bold", size=20))
#dev.off()





### PCoA
cog.cat.pcoa <- pcoa(cog.cat.dist)
  # Total variance explained = 71.4%
cog.cat.phy.ord <- cog.cat.phy
sample_data(cog.cat.phy.ord)$Season <- ordered(sample_data(cog.cat.phy.ord)$Season, levels = c("Summer", "Winter", "Spring"))


#tiff("cog.cat.pcoa.tiff", width=10, height=5, units="in", res=300)
plot_ordination(physeq = cog.cat.phy.ord, ordination = cog.cat.pcoa, axes = c(1, 2),
                color="Season") + 
  geom_point(size=5) +
  scale_color_manual(values=c("darkgoldenrod2", "dodgerblue3", "green3")) +
  ggtitle("Hellinger Distance") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(size=20),
        axis.title.y = element_text(size=20),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        plot.title = element_text(hjust=0.5, size=20))
#dev.off()
 


### Test normality
hist(cog.cat.dist)
qqnorm(cog.cat.dist)
qqline(cog.cat.dist)
shapiro.test(cog.cat.dist)
  # p-value = 0.334
  # Normal

### Run PERMANOVA on Hellinger distance
adonis(cog.cat.dist ~ Season, data=meta, permutations = 99999)
  # p-value = 0.1269
beta.tax = betadisper(d=cog.cat.dist, group=meta$Season)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.219
```



