---
title: "COG Rao Test"
author: "Edna Chiang"
date: "3/6/2021"
output: html_document
---

### Load Libraries
```{r}
library('readr')
library('pgirmess')
library('ggplot2')
library('grid')
library('phyloseq')
library('DESeq2')
library('phangorn')
library('vegan')
library('pheatmap')
library('RColorBrewer')
library('gplots')
library('tidyr')
library('dplyr')
library('stringr')
library('lme4')
library('picante')
library('ggdendro')
library('fitdistrplus')
library('amap')
library('labdsv')
library('NBPSeq')
theme_set(theme_bw())
set.seed(1)
```

### Load Functions
```{r}
source('scripts/misc.R')
source('scripts/simper.R')
source('scripts/pairwise.adonis.R')
source('scripts/anvi-script-enrichment-stats.R')
# https://github.com/merenlab/anvio/blob/master/sandbox/anvi-script-enrichment-stats
```

### COG - Load physeq objects
```{r}
load("cog.phy.Rdata")
#load("cog.cat.phy.Rdata")
meta <- read.csv('dbcan/dbcan.spades.metadata.csv', row.names=1)

cog.cat <- read.csv('cog/cog.category.raw.csv', header = T)
rownames(cog.cat) <- cog.cat[,1]
cog.cat <- cog.cat[,-1]
colnames(cog.cat) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
```

### COG Categories - Prep data
```{r}
# Load data
cog.cat.ra.phy <- transform_sample_counts(otu_table(cog.cat, taxa_are_rows = T), function(x){(x/sum(x))*100})
cog.cat.ra <- data.frame(otu_table(cog.cat.ra.phy))
colnames(cog.cat.ra) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")

# Identify potential associations btwn season & COG categories
# This is just a step to prep for Rao's test-- this association is ONLY meaningful if the categories are ACTUALLY enriched! If it's not sig in Rao, this association isn't meaningful.
# Using equation here: https://merenlab.org/2016/11/08/pangenomics-v2/#making-sense-of-functions-in-your-pangenome

cog.cat.assoc <- data.frame(matrix(ncol=6, nrow = nrow(cog.cat.ra)))
colnames(cog.cat.assoc) <- c("Season", "COG_Cat", "Expected", "Summer", "Winter", "Spring")
counter = 0
summer = which(meta$Season == "Summer")
winter = which(meta$Season == "Winter")
spring = which(meta$Season == "Spring")
seas = c("Summer", "Winter", "Spring")
for(row in 1:nrow(cog.cat.ra)){
  avgSum = sum(cog.cat.ra[row, summer])/3
  avgWin = sum(cog.cat.ra[row, winter])/3
  avgSpr = sum(cog.cat.ra[row, spring])/3
  rowSum = avgSum + avgWin + avgSpr
  expected = rowSum/3
  comb = c(avgSum, avgWin, avgSpr)
  assoc = which(c(avgSum, avgWin, avgSpr) > expected)
  numAssoc <- length(assoc)
  if (numAssoc > 0){
    counter = counter + 1
    catAssoc = str_c(seas[assoc], collapse = ",")
    cog.cat.assoc$Season[counter] = catAssoc
    catCat = rownames(cog.cat.ra[row,])
    cog.cat.assoc$COG_Cat[counter] = catCat
    cog.cat.assoc$Expected[counter] = expected
    cog.cat.assoc$Summer[counter] = avgSum
    cog.cat.assoc$Winter[counter] = avgWin
    cog.cat.assoc$Spring[counter] = avgSpr
  }
}

# Create Rao test input
cog.cat.input <- data.frame(matrix(ncol = 10, nrow = nrow(cog.cat.ra)))
colnames(cog.cat.input) = c("COG_Function", "accession", "gene_clusters_ids", "associated_groups", "p_Summer", "p_Winter", "p_Spring", "N_Summer", "N_Winter", "N_Spring")
cog.cat.input$COG_Function = c("RNA processing and modification", "Chromatin Structure and dynamics", "Energy production and conversion", "Cell cycle control and mitosis", "Amino Acid metabolis and transport", "Nucleotide metabolism and transport", "Carbohydrate metabolism and transport", "Coenzyme metabolism", "Lipid metabolism", "Translation", "Transcription", "Replication and repair", "Cell wall/membrane/envelop biogenesis", "Cell motility", "Post-translational modification, protein turnover, chaperone functions", "Inorganic ion transport and metabolism", "Secondary Structure", "General Functional Prediction only", "Function Unknown", "Signal Transduction", "Intracellular trafficing and secretion", "Defense mechanisms", "Extracellular structures", "Nuclear structure", "Cytoskeleton")
cog.cat.input$accession = cog.cat.assoc$COG_Cat
cog.cat.input$associated_groups = cog.cat.assoc$Season
cog.cat.input$p_Summer = cog.cat.assoc$Summer
cog.cat.input$p_Winter = cog.cat.assoc$Winter
cog.cat.input$p_Spring = cog.cat.assoc$Spring
cog.cat.input$N_Summer = 3
cog.cat.input$N_Winter = 3
cog.cat.input$N_Spring = 3
```