---
title: "COG test AGS"
author: "Edna Chiang"
date: "2/26/2021"
output: html_document
---

### Load Libraries
```{r}
library('readr')
library('pgirmess')
library('ggplot2')
library('grid')
library('phyloseq')
library('DESeq2')
library('phangorn')
library('vegan')
library('pheatmap')
library('RColorBrewer')
library('gplots')
library('tidyr')
library('dplyr')
library('stringr')
library('lme4')
library('picante')
library('ggdendro')
library('fitdistrplus')
library('amap')
library('labdsv')
library('NBPSeq')
theme_set(theme_bw())
set.seed(1)
```

### Load Functions
```{r}
source('scripts/misc.R')
source('scripts/simper.R')
source('scripts/pairwise.adonis.R')
```

### Create phyloseq object
```{r}
# Import raw COG count table
cog.counts <- read.csv('cog/COG.table.tab', header = T, sep = "\t")
rownames(cog.counts) <- cog.counts$COG
cog.counts <- cog.counts[,-1]
colnames(cog.counts) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")

# Identify COGs that appear in only 1 sample
cog.rem <- list()
for(i in 1:nrow(cog.counts)){
  empty <- length(which(cog.counts[i,] == 0))
    # Identifies number of samples without COG
  if(empty > 7){
    # If COG appears in only 1 sample
    cog.rem <- append(cog.rem, i)
      # Create list of COGs that appear in only 1 sample
  }
}
cog.rem.row <- as.numeric(cog.rem)
  # Convert list to numeric

# Remove COGs that appear in only 1 sample
cog.big <- cog.counts[-cog.rem.row,]
colnames(cog.big) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")

# Format data
cog.df <- data.frame(t(cog.big))
rownames(cog.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
cog.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
cog.df$Season <- ordered(cog.df$Season, levels=c("Summer", "Winter", "Spring"))

# Load COG "tax_table"
cog.cat <- read.csv('cog/cog.classifications.tab', header = T, sep = "\t")
cog.tax <- data.frame(cog.cat[,-2:-3])

# Prepare phyloseq object inputs
cog.otu <- otu_table(cog.big, taxa_are_rows = T)
cog.tax <- tax_table(cog.tax)
taxa_names(cog.tax) <- cog.tax[,1]
meta <- read.csv('dbcan/dbcan.spades.metadata.csv', row.names=1)

# Create phyloseq object
cog.phy <- merge_phyloseq(cog.otu, cog.tax, sample_data(meta))
#save(cog.phy, file = "cog.phy.Rdata")



### Category-level ###

# Create phyloseq object
colnames(cog.cat) <- c("COG", "Category", "Annotation")
cog.cat.tax <- data.frame(cog.cat$Category)
cog.cat.tax[,2] <- cog.cat$COG
colnames(cog.cat.tax) <- c("Category", "COG")
cog.cat.tax <- tax_table(cog.cat.tax)
taxa_names(cog.cat.tax) <- cog.cat.tax[,2]
colnames(tax_table(cog.cat.tax)) <- c("Category", "COG")
cog.cat.phy <- merge_phyloseq(cog.otu, cog.cat.tax, sample_data(meta))

# Merge by category
cog.cat.phy <- tax_glom(cog.cat.phy, taxrank = "Category")

```
### MicrobeCensus - Average Genome Size
```{r}
# Load data
mc <- read.csv('MicrobeCensus/Summary.csv', row.names = 1)
mc.ma <- as.matrix(mc)

# Test normality
hist(mc.ma[2,])
qqnorm(mc.ma[2,])
qqline(mc.ma[2,])
shapiro.test(mc.ma[2,])
  # p-value = 0.03487
  # Not Normal

# Format for Kruskal-Wallis
mc <- t(mc)
mc <- data.frame(mc)
mc$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
mc$Season <- ordered(mc$Season, levels=c("Summer", "Winter", "Spring"))

# Kruskal-Wallis
kruskal.test(formula = AGS ~ Season, data = mc)
  # p-value = 0.4298
```
### Divide counts by AGS
```{r}
# Normalize COG counts by dividing by each sample's average genome size
cog.norm <- data.frame(matrix(nrow = nrow(cog.counts), ncol = ncol(cog.counts)))
rownames(cog.norm) <- rownames(cog.counts)
colnames(cog.norm) <- colnames(cog.counts)
for(i in 1:ncol(cog.counts)){
 cog.norm[,i] = cog.counts[,i] / mc.ma[2,i]
}


# Normalize COG category counts by dividing by each sample's average genome size
cog.cat <- read.csv('cog/cog.category.raw.csv', header = T)
rownames(cog.cat) <- cog.cat[,1]
cog.cat <- cog.cat[,-1]
colnames(cog.cat) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
cog.cat.norm <- data.frame(matrix(nrow = 25, ncol = 9))
rownames(cog.cat.norm) <- rownames(cog.cat)
colnames(cog.cat.norm) <- colnames(cog.cat)
for(i in 1:ncol(cog.cat)){
 cog.cat.norm[,i] = cog.cat[,i] / mc.ma[2,i]
}

```

### COG Category - Kruskal-Wallis
```{r}
# Format data
cog.cat.df <- data.frame(t(cog.cat.norm))
cog.cat.df$Season <- c("Summer", "Summer", "Winter", "Winter", "Spring", "Summer", "Winter", "Spring", "Spring")
cog.cat.df$Season <- ordered(cog.cat.df$Season, levels=c("Summer", "Winter", "Spring"))
cog.cat.mat <- as.matrix(t(cog.cat.df))


# Run Kruskal-Wallis on all categories
cog.cat.kw <- data.frame(matrix(nrow = 1, ncol = nrow(cog.cat)))
colnames(cog.cat.kw) <- rownames(cog.cat)
for(i in 1:nrow(cog.cat)){
  cogName <- colnames(cog.cat.df)[i]
  kw <- kruskal.test(formula = reformulate("Season", cogName), data = cog.cat.df)
  cog.cat.kw[,i] <- kw$p.value
}
cog.cat.kw[2,] <- p.adjust(cog.cat.kw[1,], method = "fdr")
which(cog.cat.kw[2,] < 0.05)


pairwise.wilcox.test(x = cog.cat.df$A, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$B, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$C, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$D, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$E, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$F, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$G, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$H, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$I, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$J, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$K, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$L, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$M, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$N, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$O, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$P, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$Q, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$R, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$S, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$T, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$U, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$V, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$W, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$Y, g = cog.cat.df$Season, p.adjust.method = "BH")
pairwise.wilcox.test(x = cog.cat.df$Z, g = cog.cat.df$Season, p.adjust.method = "BH")


summary(aov(A ~ Season, data = cog.cat.df))
summary(aov(B ~ Season, data = cog.cat.df))
summary(aov(C ~ Season, data = cog.cat.df))
summary(aov(D ~ Season, data = cog.cat.df))
summary(aov(E ~ Season, data = cog.cat.df))
summary(aov(F ~ Season, data = cog.cat.df))
summary(aov(G ~ Season, data = cog.cat.df))
summary(aov(H ~ Season, data = cog.cat.df))
summary(aov(I ~ Season, data = cog.cat.df))
summary(aov(J ~ Season, data = cog.cat.df))
summary(aov(K ~ Season, data = cog.cat.df))
summary(aov(L ~ Season, data = cog.cat.df))
summary(aov(M ~ Season, data = cog.cat.df))
summary(aov(N ~ Season, data = cog.cat.df))
summary(aov(O ~ Season, data = cog.cat.df))
summary(aov(P ~ Season, data = cog.cat.df))
summary(aov(Q ~ Season, data = cog.cat.df))
summary(aov(R ~ Season, data = cog.cat.df))
summary(aov(S ~ Season, data = cog.cat.df))
summary(aov(T ~ Season, data = cog.cat.df))
summary(aov(U ~ Season, data = cog.cat.df))
summary(aov(V ~ Season, data = cog.cat.df))
summary(aov(W ~ Season, data = cog.cat.df))
summary(aov(Y ~ Season, data = cog.cat.df))
summary(aov(Z ~ Season, data = cog.cat.df))





### Try Diet
# Format data
cog.cat.df <- data.frame(t(cog.cat))
rownames(cog.cat.df) <- c("3715", "3717", "3723", "3733", "3734", "3744", "3772", "3773", "3775")
cog.cat.df$Diet <- c("Feed", "Feed", "Fast", "Fast", "Feed", "Feed", "Fast", "Feed", "Feed")
cog.cat.df$Diet <- ordered(cog.cat.df$Diet, levels=c("Feed", "Fast"))
cog.cat.mat <- as.matrix((cog.cat.df))
DietVar <- cog.cat.df$Diet

# Run Wilcoxon on all COGs
cog.cat.wil <- data.frame(matrix(nrow = 1, ncol = nrow(cog.cat)))
colnames(cog.cat.wil) <- rownames(cog.cat)
for(i in 1:nrow(cog.cat)){
  cogName <- colnames(cog.cat.df)[i]
  wil <- wilcox.test(as.numeric(cog.cat.mat[,i]) ~ DietVar, cog.cat.mat)
    cog.cat.wil[,i] <- wil$p.value
}
cog.cat.wil[2,] <- p.adjust(cog.cat.wil[1,], method = "fdr")
which(cog.cat.wil[2,] < 0.05)

```